// class generated by JConcept Database ClassBuilder 2.0
package org.neodatis.rdb.test;

// import JConcept Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import org.neodatis.rdb.implementation.*;

// For Date attribute
import java.util.Date;

// For BigDecimal attribute
import java.math.*;

public class Evento extends Object  implements DbObjectMapping 
{
	//** Database fields
	protected Long dbID;
	protected String dbUUID;
	protected Long dbNUMERO;
	protected Long dbID_CATEGORIA;
	protected Long dbID_TIPO;
	protected Long dbID_SUB_TIPO;
	protected Long dbID_CENTRO_CONTROLE;
	protected String dbOBSERVACAO;
	protected Long dbID_ESTADO;
	protected Long dbID_RODOVIA;
	protected Long dbID_SENTIDO;
	protected Long dbFAIXA;
	protected BigDecimal dbKM;
	protected String dbENDERECO;
	protected String dbREFERENCIA_ENDERECO;
	protected BigDecimal dbLONGITUDE;
	protected BigDecimal dbLATITUDE;
	protected Date dbDATA_HORA_CRIACAO_EVENTO;
	protected Date dbDATA_HORA_INICIO_EVENTO;
	protected Date dbDATA_HORA_ATUALIZACAO_EVENTO;
	protected Date dbDATA_HORA_TERMINO_DIGITADO;
	protected Long dbPRIORIDADE;
	protected Long dbID_ORIGEM_EVENTO;
	protected String dbDESCRICAO_ORIGEM_EVENTO;
	protected Long dbID_SITUACAO_EVENTO;
	protected Long dbID_RAZAO_FECHAMENTO;
	protected Long dbID_OPERADOR_RESPONSAVEL;
	protected String dbID_EXTERNO;

	//** Construtor
	public Evento()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("ID");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("EVENTIS_EVENTO");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbID = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbID;
	}

	// Setter for attribute uuid
	public void setUuid( String in_uuid ) 
	{
		dbUUID = in_uuid;
	}

	// Getter for attribute uuid
	public String getUuid()
	{
		return dbUUID;
	}

	// Setter for attribute numero
	public void setNumero( Long in_numero ) 
	{
		dbNUMERO = in_numero;
	}

	// Getter for attribute numero
	public Long getNumero()
	{
		return dbNUMERO;
	}

	// Setter for attribute idCategoria
	public void setIdCategoria( Long in_idCategoria ) 
	{
		dbID_CATEGORIA = in_idCategoria;
	}

	// Getter for attribute idCategoria
	public Long getIdCategoria()
	{
		return dbID_CATEGORIA;
	}

	// Setter for attribute idTipo
	public void setIdTipo( Long in_idTipo ) 
	{
		dbID_TIPO = in_idTipo;
	}

	// Getter for attribute idTipo
	public Long getIdTipo()
	{
		return dbID_TIPO;
	}

	// Setter for attribute idSubTipo
	public void setIdSubTipo( Long in_idSubTipo ) 
	{
		dbID_SUB_TIPO = in_idSubTipo;
	}

	// Getter for attribute idSubTipo
	public Long getIdSubTipo()
	{
		return dbID_SUB_TIPO;
	}

	// Setter for attribute idCentroControle
	public void setIdCentroControle( Long in_idCentroControle ) 
	{
		dbID_CENTRO_CONTROLE = in_idCentroControle;
	}

	// Getter for attribute idCentroControle
	public Long getIdCentroControle()
	{
		return dbID_CENTRO_CONTROLE;
	}

	// Setter for attribute observacao
	public void setObservacao( String in_observacao ) 
	{
		dbOBSERVACAO = in_observacao;
	}

	// Getter for attribute observacao
	public String getObservacao()
	{
		return dbOBSERVACAO;
	}

	// Setter for attribute idEstado
	public void setIdEstado( Long in_idEstado ) 
	{
		dbID_ESTADO = in_idEstado;
	}

	// Getter for attribute idEstado
	public Long getIdEstado()
	{
		return dbID_ESTADO;
	}

	// Setter for attribute idRodovia
	public void setIdRodovia( Long in_idRodovia ) 
	{
		dbID_RODOVIA = in_idRodovia;
	}

	// Getter for attribute idRodovia
	public Long getIdRodovia()
	{
		return dbID_RODOVIA;
	}

	// Setter for attribute idSentido
	public void setIdSentido( Long in_idSentido ) 
	{
		dbID_SENTIDO = in_idSentido;
	}

	// Getter for attribute idSentido
	public Long getIdSentido()
	{
		return dbID_SENTIDO;
	}

	// Setter for attribute faixa
	public void setFaixa( Long in_faixa ) 
	{
		dbFAIXA = in_faixa;
	}

	// Getter for attribute faixa
	public Long getFaixa()
	{
		return dbFAIXA;
	}

	// Setter for attribute km
	public void setKm( BigDecimal in_km ) 
	{
		dbKM = in_km;
	}

	// Getter for attribute km
	public BigDecimal getKm()
	{
		return dbKM;
	}

	// Setter for attribute endereco
	public void setEndereco( String in_endereco ) 
	{
		dbENDERECO = in_endereco;
	}

	// Getter for attribute endereco
	public String getEndereco()
	{
		return dbENDERECO;
	}

	// Setter for attribute referenciaEndereco
	public void setReferenciaEndereco( String in_referenciaEndereco ) 
	{
		dbREFERENCIA_ENDERECO = in_referenciaEndereco;
	}

	// Getter for attribute referenciaEndereco
	public String getReferenciaEndereco()
	{
		return dbREFERENCIA_ENDERECO;
	}

	// Setter for attribute longitude
	public void setLongitude( BigDecimal in_longitude ) 
	{
		dbLONGITUDE = in_longitude;
	}

	// Getter for attribute longitude
	public BigDecimal getLongitude()
	{
		return dbLONGITUDE;
	}

	// Setter for attribute latitude
	public void setLatitude( BigDecimal in_latitude ) 
	{
		dbLATITUDE = in_latitude;
	}

	// Getter for attribute latitude
	public BigDecimal getLatitude()
	{
		return dbLATITUDE;
	}

	// Setter for attribute dataHoraCriacaoEvento
	public void setDataHoraCriacaoEvento( Date in_dataHoraCriacaoEvento ) 
	{
		dbDATA_HORA_CRIACAO_EVENTO = in_dataHoraCriacaoEvento;
	}

	// Getter for attribute dataHoraCriacaoEvento
	public Date getDataHoraCriacaoEvento()
	{
		return dbDATA_HORA_CRIACAO_EVENTO;
	}

	// Setter for attribute dataHoraInicioEvento
	public void setDataHoraInicioEvento( Date in_dataHoraInicioEvento ) 
	{
		dbDATA_HORA_INICIO_EVENTO = in_dataHoraInicioEvento;
	}

	// Getter for attribute dataHoraInicioEvento
	public Date getDataHoraInicioEvento()
	{
		return dbDATA_HORA_INICIO_EVENTO;
	}

	// Setter for attribute dataHoraAtualizacaoEvento
	public void setDataHoraAtualizacaoEvento( Date in_dataHoraAtualizacaoEvento ) 
	{
		dbDATA_HORA_ATUALIZACAO_EVENTO = in_dataHoraAtualizacaoEvento;
	}

	// Getter for attribute dataHoraAtualizacaoEvento
	public Date getDataHoraAtualizacaoEvento()
	{
		return dbDATA_HORA_ATUALIZACAO_EVENTO;
	}

	// Setter for attribute dataHoraTerminoDigitado
	public void setDataHoraTerminoDigitado( Date in_dataHoraTerminoDigitado ) 
	{
		dbDATA_HORA_TERMINO_DIGITADO = in_dataHoraTerminoDigitado;
	}

	// Getter for attribute dataHoraTerminoDigitado
	public Date getDataHoraTerminoDigitado()
	{
		return dbDATA_HORA_TERMINO_DIGITADO;
	}

	// Setter for attribute prioridade
	public void setPrioridade( Long in_prioridade ) 
	{
		dbPRIORIDADE = in_prioridade;
	}

	// Getter for attribute prioridade
	public Long getPrioridade()
	{
		return dbPRIORIDADE;
	}

	// Setter for attribute idOrigemEvento
	public void setIdOrigemEvento( Long in_idOrigemEvento ) 
	{
		dbID_ORIGEM_EVENTO = in_idOrigemEvento;
	}

	// Getter for attribute idOrigemEvento
	public Long getIdOrigemEvento()
	{
		return dbID_ORIGEM_EVENTO;
	}

	// Setter for attribute descricaoOrigemEvento
	public void setDescricaoOrigemEvento( String in_descricaoOrigemEvento ) 
	{
		dbDESCRICAO_ORIGEM_EVENTO = in_descricaoOrigemEvento;
	}

	// Getter for attribute descricaoOrigemEvento
	public String getDescricaoOrigemEvento()
	{
		return dbDESCRICAO_ORIGEM_EVENTO;
	}

	// Setter for attribute idSituacaoEvento
	public void setIdSituacaoEvento( Long in_idSituacaoEvento ) 
	{
		dbID_SITUACAO_EVENTO = in_idSituacaoEvento;
	}

	// Getter for attribute idSituacaoEvento
	public Long getIdSituacaoEvento()
	{
		return dbID_SITUACAO_EVENTO;
	}

	// Setter for attribute idRazaoFechamento
	public void setIdRazaoFechamento( Long in_idRazaoFechamento ) 
	{
		dbID_RAZAO_FECHAMENTO = in_idRazaoFechamento;
	}

	// Getter for attribute idRazaoFechamento
	public Long getIdRazaoFechamento()
	{
		return dbID_RAZAO_FECHAMENTO;
	}

	// Setter for attribute idOperadorResponsavel
	public void setIdOperadorResponsavel( Long in_idOperadorResponsavel ) 
	{
		dbID_OPERADOR_RESPONSAVEL = in_idOperadorResponsavel;
	}

	// Getter for attribute idOperadorResponsavel
	public Long getIdOperadorResponsavel()
	{
		return dbID_OPERADOR_RESPONSAVEL;
	}

	// Setter for attribute idExterno
	public void setIdExterno( String in_idExterno ) 
	{
		dbID_EXTERNO = in_idExterno;
	}

	// Getter for attribute idExterno
	public String getIdExterno()
	{
		return dbID_EXTERNO;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t uuid : " ).append( getUuid()).append("\n");
		sResult.append( "\t numero : " ).append( getNumero()).append("\n");
		sResult.append( "\t idCategoria : " ).append( getIdCategoria()).append("\n");
		sResult.append( "\t idTipo : " ).append( getIdTipo()).append("\n");
		sResult.append( "\t idSubTipo : " ).append( getIdSubTipo()).append("\n");
		sResult.append( "\t idCentroControle : " ).append( getIdCentroControle()).append("\n");
		sResult.append( "\t observacao : " ).append( getObservacao()).append("\n");
		sResult.append( "\t idEstado : " ).append( getIdEstado()).append("\n");
		sResult.append( "\t idRodovia : " ).append( getIdRodovia()).append("\n");
		sResult.append( "\t idSentido : " ).append( getIdSentido()).append("\n");
		sResult.append( "\t faixa : " ).append( getFaixa()).append("\n");
		sResult.append( "\t km : " ).append( getKm()).append("\n");
		sResult.append( "\t endereco : " ).append( getEndereco()).append("\n");
		sResult.append( "\t referenciaEndereco : " ).append( getReferenciaEndereco()).append("\n");
		sResult.append( "\t longitude : " ).append( getLongitude()).append("\n");
		sResult.append( "\t latitude : " ).append( getLatitude()).append("\n");
		sResult.append( "\t dataHoraCriacaoEvento : " ).append( getDataHoraCriacaoEvento()).append("\n");
		sResult.append( "\t dataHoraInicioEvento : " ).append( getDataHoraInicioEvento()).append("\n");
		sResult.append( "\t dataHoraAtualizacaoEvento : " ).append( getDataHoraAtualizacaoEvento()).append("\n");
		sResult.append( "\t dataHoraTerminoDigitado : " ).append( getDataHoraTerminoDigitado()).append("\n");
		sResult.append( "\t prioridade : " ).append( getPrioridade()).append("\n");
		sResult.append( "\t idOrigemEvento : " ).append( getIdOrigemEvento()).append("\n");
		sResult.append( "\t descricaoOrigemEvento : " ).append( getDescricaoOrigemEvento()).append("\n");
		sResult.append( "\t idSituacaoEvento : " ).append( getIdSituacaoEvento()).append("\n");
		sResult.append( "\t idRazaoFechamento : " ).append( getIdRazaoFechamento()).append("\n");
		sResult.append( "\t idOperadorResponsavel : " ).append( getIdOperadorResponsavel()).append("\n");
		sResult.append( "\t idExterno : " ).append( getIdExterno()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

}
	//** Database fields
