// class generated by JConcept Database ClassBuilder 2.0
package com.mycompany.myobjects;

// import JConcept Database library
import br.com.jconcept.database.*;

import br.com.jconcept.database.query.*;

import br.com.jconcept.database.implementation.*;

// For Date attribute
import java.util.Date;

// For BigDecimal attribute
import java.math.*;

public class Client extends Object  implements DbObjectMapping 
{
	//** Database fields
	protected Long dbCLIENT_ID;
	protected String dbNAME;
	protected String dbLAST_NAME;
	protected Date dbBIRTH_DATE;
	protected String dbSTREET;
	protected Long dbSTREET_NUMBER;
	protected Double dbDEBIT;
	protected Double dbCREDIT;

	//** Construtor
	public Client()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("CLIENT_ID");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("CLIENT");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute clientId
	public void setClientId( Long in_clientId ) 
	{
		dbCLIENT_ID = in_clientId;
	}

	// Getter for attribute clientId
	public Long getClientId()
	{
		return dbCLIENT_ID;
	}

	// Setter for attribute name
	public void setName( String in_name ) 
	{
		dbNAME = in_name;
	}

	// Getter for attribute name
	public String getName()
	{
		return dbNAME;
	}

	// Setter for attribute lastName
	public void setLastName( String in_lastName ) 
	{
		dbLAST_NAME = in_lastName;
	}

	// Getter for attribute lastName
	public String getLastName()
	{
		return dbLAST_NAME;
	}

	// Setter for attribute birthDate
	public void setBirthDate( Date in_birthDate ) 
	{
		dbBIRTH_DATE = in_birthDate;
	}

	// Getter for attribute birthDate
	public Date getBirthDate()
	{
		return dbBIRTH_DATE;
	}

	// Setter for attribute street
	public void setStreet( String in_street ) 
	{
		dbSTREET = in_street;
	}

	// Getter for attribute street
	public String getStreet()
	{
		return dbSTREET;
	}

	// Setter for attribute streetNumber
	public void setStreetNumber( Long in_streetNumber ) 
	{
		dbSTREET_NUMBER = in_streetNumber;
	}

	// Getter for attribute streetNumber
	public Long getStreetNumber()
	{
		return dbSTREET_NUMBER;
	}

	// Setter for attribute debit
	public void setDebit( Double in_debit ) 
	{
		dbDEBIT = in_debit;
	}

	// Getter for attribute debit
	public Double getDebit()
	{
		return dbDEBIT;
	}

	// Setter for attribute credit
	public void setCredit( Double in_credit ) 
	{
		dbCREDIT = in_credit;
	}

	// Getter for attribute credit
	public Double getCredit()
	{
		return dbCREDIT;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t clientId : " ).append( getClientId()).append("\n");
		sResult.append( "\t name : " ).append( getName()).append("\n");
		sResult.append( "\t lastName : " ).append( getLastName()).append("\n");
		sResult.append( "\t birthDate : " ).append( getBirthDate()).append("\n");
		sResult.append( "\t street : " ).append( getStreet()).append("\n");
		sResult.append( "\t streetNumber : " ).append( getStreetNumber()).append("\n");
		sResult.append( "\t debit : " ).append( getDebit()).append("\n");
		sResult.append( "\t credit : " ).append( getCredit()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

}
	//** Database fields
