// class generated by JConcept Database ClassBuilder 2.0
package com.mycompany.myobjects;

// import JConcept Database library
import br.com.jconcept.database.*;

import br.com.jconcept.database.query.*;

import br.com.jconcept.database.implementation.*;

// For Date attribute
import java.util.Date;

// For BigDecimal attribute
import java.math.*;

public class Product extends Object  implements DbObjectMapping 
{
	//** Database fields
	protected Long dbPRODUCT_ID;
	protected String dbNAME;
	protected String dbDESCRIPTION;
	protected Double dbUNIT_PRICE;

	//** Construtor
	public Product()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("PRODUCT_ID");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("PRODUCT");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute productId
	public void setProductId( Long in_productId ) 
	{
		dbPRODUCT_ID = in_productId;
	}

	// Getter for attribute productId
	public Long getProductId()
	{
		return dbPRODUCT_ID;
	}

	// Setter for attribute name
	public void setName( String in_name ) 
	{
		dbNAME = in_name;
	}

	// Getter for attribute name
	public String getName()
	{
		return dbNAME;
	}

	// Setter for attribute description
	public void setDescription( String in_description ) 
	{
		dbDESCRIPTION = in_description;
	}

	// Getter for attribute description
	public String getDescription()
	{
		return dbDESCRIPTION;
	}

	// Setter for attribute unitPrice
	public void setUnitPrice( Double in_unitPrice ) 
	{
		dbUNIT_PRICE = in_unitPrice;
	}

	// Getter for attribute unitPrice
	public Double getUnitPrice()
	{
		return dbUNIT_PRICE;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t productId : " ).append( getProductId()).append("\n");
		sResult.append( "\t name : " ).append( getName()).append("\n");
		sResult.append( "\t description : " ).append( getDescription()).append("\n");
		sResult.append( "\t unitPrice : " ).append( getUnitPrice()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

}
	//** Database fields
