// class generated by JConcept Database ClassBuilder 2.0
package com.mycompany.myobjects;

// import JConcept Database library
import br.com.jconcept.database.*;

import br.com.jconcept.database.query.*;

import br.com.jconcept.database.implementation.*;

// For Date attribute
import java.util.Date;

// For BigDecimal attribute
import java.math.*;

public class Sale extends Object  implements DbObjectMapping 
{
	//** Database fields
	protected Long dbSALE_ID;
	protected Long dbCLIENT_ID;
	protected Long dbPRODUCT_ID;
	protected Date dbSALE_DATE;
	protected Long dbQUANTITY;

	//** Construtor
	public Sale()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("SALE_ID");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("SALE");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute saleId
	public void setSaleId( Long in_saleId ) 
	{
		dbSALE_ID = in_saleId;
	}

	// Getter for attribute saleId
	public Long getSaleId()
	{
		return dbSALE_ID;
	}

	// Setter for attribute clientId
	public void setClientId( Long in_clientId ) 
	{
		dbCLIENT_ID = in_clientId;
	}

	// Getter for attribute clientId
	public Long getClientId()
	{
		return dbCLIENT_ID;
	}

	// Setter for attribute productId
	public void setProductId( Long in_productId ) 
	{
		dbPRODUCT_ID = in_productId;
	}

	// Getter for attribute productId
	public Long getProductId()
	{
		return dbPRODUCT_ID;
	}

	// Setter for attribute saleDate
	public void setSaleDate( Date in_saleDate ) 
	{
		dbSALE_DATE = in_saleDate;
	}

	// Getter for attribute saleDate
	public Date getSaleDate()
	{
		return dbSALE_DATE;
	}

	// Setter for attribute quantity
	public void setQuantity( Long in_quantity ) 
	{
		dbQUANTITY = in_quantity;
	}

	// Getter for attribute quantity
	public Long getQuantity()
	{
		return dbQUANTITY;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t saleId : " ).append( getSaleId()).append("\n");
		sResult.append( "\t clientId : " ).append( getClientId()).append("\n");
		sResult.append( "\t productId : " ).append( getProductId()).append("\n");
		sResult.append( "\t saleDate : " ).append( getSaleDate()).append("\n");
		sResult.append( "\t quantity : " ).append( getQuantity()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

}
	//** Database fields
