// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.test.test1.meta;

// import NeoDatis Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import java.util.Date;

import java.math.BigDecimal;

public class Table1DBHelper{
	public static final DBTable table = new DefaultDBTable("PUBLIC.TABLE1");


	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[0];
		return array;
	}
}
