// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model.meta;

// import NeoDatis Database library
import org.neodatis.rdb.DBColumn;
import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.query.DefaultDBColumn;
import org.neodatis.rdb.query.DefaultDBTable;

public class CompanyDBHelper{
	public static final DBTable table = new DefaultDBTable("company");

	public static final DBColumn ID =  new DefaultDBColumn( table , "id" , Long.class );
	public static final DBColumn NAME =  new DefaultDBColumn( table , "name" , String.class );
	public static final DBColumn STATUS =  new DefaultDBColumn( table , "status" , Long.class );
	public static final DBColumn DELETED =  new DefaultDBColumn( table , "deleted" , Long.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[4];
		array[0] = ID;
		array[1] = NAME;
		array[2] = STATUS;
		array[3] = DELETED;
		return array;
	}
}
