// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model.meta;

// import NeoDatis Database library
import java.util.Date;

import org.neodatis.rdb.DBColumn;
import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.query.DefaultDBColumn;
import org.neodatis.rdb.query.DefaultDBTable;

public class EventDBHelper{
	public static final DBTable table = new DefaultDBTable("event");

	public static final DBColumn ID =  new DefaultDBColumn( table , "id" , Long.class );
	public static final DBColumn DATE =  new DefaultDBColumn( table , "date" , Date.class );
	public static final DBColumn EQUIPMENT_TYPE =  new DefaultDBColumn( table , "equipment_type" , String.class );
	public static final DBColumn ALARME_TYPE =  new DefaultDBColumn( table , "alarme_type" , String.class );
	public static final DBColumn EQUIPMENT_NAME =  new DefaultDBColumn( table , "equipment_name" , String.class );
	public static final DBColumn EQUIPMENT_ID =  new DefaultDBColumn( table , "equipment_id" , Long.class );
	public static final DBColumn DESCRIPTION =  new DefaultDBColumn( table , "description" , String.class );
	public static final DBColumn EXTERNAL_ID =  new DefaultDBColumn( table , "external_id" , String.class );
	public static final DBColumn PARAMETER1 =  new DefaultDBColumn( table , "parameter1" , String.class );
	public static final DBColumn PARAMETER2 =  new DefaultDBColumn( table , "parameter2" , String.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[10];
		array[0] = ID;
		array[1] = DATE;
		array[2] = EQUIPMENT_TYPE;
		array[3] = ALARME_TYPE;
		array[4] = EQUIPMENT_NAME;
		array[5] = EQUIPMENT_ID;
		array[6] = DESCRIPTION;
		array[7] = EXTERNAL_ID;
		array[8] = PARAMETER1;
		array[9] = PARAMETER2;
		return array;
	}
}
