// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model.meta;

// import NeoDatis Database library
import java.math.BigDecimal;
import java.util.Date;

import org.neodatis.rdb.DBColumn;
import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.query.DefaultDBColumn;
import org.neodatis.rdb.query.DefaultDBTable;

public class PnDataDBHelper{
	public static final DBTable table = new DefaultDBTable("pn_data");

	public static final DBColumn ID =  new DefaultDBColumn( table , "id" , Long.class );
	public static final DBColumn NAME =  new DefaultDBColumn( table , "name" , String.class );
	public static final DBColumn UP_NAME =  new DefaultDBColumn( table , "up_name" , String.class );
	public static final DBColumn KM =  new DefaultDBColumn( table , "km" , String.class );
	public static final DBColumn DATE =  new DefaultDBColumn( table , "date" , Date.class );
	public static final DBColumn INPUT1 =  new DefaultDBColumn( table , "input1" , Long.class );
	public static final DBColumn INPUT2 =  new DefaultDBColumn( table , "input2" , Long.class );
	public static final DBColumn INPUT3 =  new DefaultDBColumn( table , "input3" , Long.class );
	public static final DBColumn INPUT4 =  new DefaultDBColumn( table , "input4" , Long.class );
	public static final DBColumn INPUT5 =  new DefaultDBColumn( table , "input5" , Long.class );
	public static final DBColumn INPUT6 =  new DefaultDBColumn( table , "input6" , Long.class );
	public static final DBColumn OUTPUT1 =  new DefaultDBColumn( table , "output1" , Long.class );
	public static final DBColumn VOLTAGE =  new DefaultDBColumn( table , "voltage" , BigDecimal.class );
	public static final DBColumn CELL_LEVEL =  new DefaultDBColumn( table , "cell_level" , BigDecimal.class );
	public static final DBColumn UP_ID =  new DefaultDBColumn( table , "up_id" , Long.class );
	public static final DBColumn PN_ID =  new DefaultDBColumn( table , "pn_id" , Long.class );
	public static final DBColumn TYPE =  new DefaultDBColumn( table , "type" , Long.class );
	public static final DBColumn VOLTAGE_SLAVE =  new DefaultDBColumn( table , "voltage_slave" , BigDecimal.class );
	public static final DBColumn PN_TYPE =  new DefaultDBColumn( table , "pn_type" , Long.class );
	public static final DBColumn LAST_DETECTION_START_DATE =  new DefaultDBColumn( table , "last_detection_start_date" , Date.class );
	public static final DBColumn LAST_DETECTION_END_DATE =  new DefaultDBColumn( table , "last_detection_end_date" , Date.class );
	public static final DBColumn SENSOR7 =  new DefaultDBColumn( table , "sensor7" , Long.class );
	public static final DBColumn SENSOR8 =  new DefaultDBColumn( table , "sensor8" , Long.class );
	public static final DBColumn SENSOR2 =  new DefaultDBColumn( table , "sensor2" , Long.class );
	public static final DBColumn SENSOR3 =  new DefaultDBColumn( table , "sensor3" , Long.class );
	public static final DBColumn SENSOR4 =  new DefaultDBColumn( table , "sensor4" , Long.class );
	public static final DBColumn SENSOR5 =  new DefaultDBColumn( table , "sensor5" , Long.class );
	public static final DBColumn SENSOR6 =  new DefaultDBColumn( table , "sensor6" , Long.class );
	public static final DBColumn DEVICE_LAST_DETECTED_SPEED =  new DefaultDBColumn( table , "device_last_detected_speed" , BigDecimal.class );
	public static final DBColumn DEVICE_LAST_NUMBER_OF_EIXOS =  new DefaultDBColumn( table , "device_last_number_of_eixos" , Long.class );
	public static final DBColumn DEVICE_LAST_DETECTED_WEIGHT =  new DefaultDBColumn( table , "device_last_detected_weight" , BigDecimal.class );
	public static final DBColumn DEVICE_LAST_DETECTED_TEMPERATURE =  new DefaultDBColumn( table , "device_last_detected_temperature" , Long.class );
	public static final DBColumn SENSOR1 =  new DefaultDBColumn( table , "sensor1" , Long.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[33];
		array[0] = ID;
		array[1] = NAME;
		array[2] = UP_NAME;
		array[3] = KM;
		array[4] = DATE;
		array[5] = INPUT1;
		array[6] = INPUT2;
		array[7] = INPUT3;
		array[8] = INPUT4;
		array[9] = INPUT5;
		array[10] = INPUT6;
		array[11] = OUTPUT1;
		array[12] = VOLTAGE;
		array[13] = CELL_LEVEL;
		array[14] = UP_ID;
		array[15] = PN_ID;
		array[16] = TYPE;
		array[17] = VOLTAGE_SLAVE;
		array[18] = PN_TYPE;
		array[19] = LAST_DETECTION_START_DATE;
		array[20] = LAST_DETECTION_END_DATE;
		array[21] = SENSOR7;
		array[22] = SENSOR8;
		array[23] = SENSOR2;
		array[24] = SENSOR3;
		array[25] = SENSOR4;
		array[26] = SENSOR5;
		array[27] = SENSOR6;
		array[28] = DEVICE_LAST_DETECTED_SPEED;
		array[29] = DEVICE_LAST_NUMBER_OF_EIXOS;
		array[30] = DEVICE_LAST_DETECTED_WEIGHT;
		array[31] = DEVICE_LAST_DETECTED_TEMPERATURE;
		array[32] = SENSOR1;
		return array;
	}
}
