// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model.meta;

// import NeoDatis Database library
import java.math.BigDecimal;
import java.util.Date;

import org.neodatis.rdb.DBColumn;
import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.query.DefaultDBColumn;
import org.neodatis.rdb.query.DefaultDBTable;

public class PnDBHelper{
	public static final DBTable table = new DefaultDBTable("pn");

	public static final DBColumn ID =  new DefaultDBColumn( table , "id" , Long.class );
	public static final DBColumn EXTERNAL_ID =  new DefaultDBColumn( table , "external_id" , Long.class );
	public static final DBColumn NAME =  new DefaultDBColumn( table , "name" , String.class );
	public static final DBColumn EXTERNAL_NAME =  new DefaultDBColumn( table , "external_name" , String.class );
	public static final DBColumn UP_ID =  new DefaultDBColumn( table , "up_id" , Long.class );
	public static final DBColumn KM =  new DefaultDBColumn( table , "km" , BigDecimal.class );
	public static final DBColumn LOCAL =  new DefaultDBColumn( table , "local" , String.class );
	public static final DBColumn LAST_DATA_DATE =  new DefaultDBColumn( table , "last_data_date" , Date.class );
	public static final DBColumn LAST_ACTIVATION_DATE =  new DefaultDBColumn( table , "last_activation_date" , Date.class );
	public static final DBColumn CREATION_DATE =  new DefaultDBColumn( table , "creation_date" , Date.class );
	public static final DBColumn UPDATE_DATE =  new DefaultDBColumn( table , "update_date" , Date.class );
	public static final DBColumn INPUT1 =  new DefaultDBColumn( table , "input1" , Long.class );
	public static final DBColumn INPUT2 =  new DefaultDBColumn( table , "input2" , Long.class );
	public static final DBColumn INPUT3 =  new DefaultDBColumn( table , "input3" , Long.class );
	public static final DBColumn INPUT4 =  new DefaultDBColumn( table , "input4" , Long.class );
	public static final DBColumn INPUT5 =  new DefaultDBColumn( table , "input5" , Long.class );
	public static final DBColumn INPUT6 =  new DefaultDBColumn( table , "input6" , Long.class );
	public static final DBColumn OUTPUT =  new DefaultDBColumn( table , "output" , Long.class );
	public static final DBColumn VOLTAGE =  new DefaultDBColumn( table , "voltage" , BigDecimal.class );
	public static final DBColumn CELL_LEVEL =  new DefaultDBColumn( table , "cell_level" , BigDecimal.class );
	public static final DBColumn LATITUDE =  new DefaultDBColumn( table , "latitude" , BigDecimal.class );
	public static final DBColumn LONGITUDE =  new DefaultDBColumn( table , "longitude" , BigDecimal.class );
	public static final DBColumn STATUS =  new DefaultDBColumn( table , "status" , Long.class );
	public static final DBColumn DELETED =  new DefaultDBColumn( table , "deleted" , Long.class );
	public static final DBColumn VOLTAGE_SLAVE =  new DefaultDBColumn( table , "voltage_slave" , BigDecimal.class );
	public static final DBColumn TYPE =  new DefaultDBColumn( table , "type" , Long.class );
	public static final DBColumn PN_TYPE =  new DefaultDBColumn( table , "pn_type" , Long.class );
	public static final DBColumn DEVICE_LAST_DETECTED_SPEED =  new DefaultDBColumn( table , "device_last_detected_speed" , BigDecimal.class );
	public static final DBColumn DEVICE_LAST_NUMBER_OF_EIXOS =  new DefaultDBColumn( table , "device_last_number_of_eixos" , Long.class );
	public static final DBColumn DEVICE_LAST_DETECTED_WEIGHT =  new DefaultDBColumn( table , "device_last_detected_weight" , BigDecimal.class );
	public static final DBColumn LAST_DETECTION_START_DATE =  new DefaultDBColumn( table , "last_detection_start_date" , Date.class );
	public static final DBColumn LAST_DETECTION_END_DATE =  new DefaultDBColumn( table , "last_detection_end_date" , Date.class );
	public static final DBColumn DEVICE_LAST_DETECTED_TEMPERATURE =  new DefaultDBColumn( table , "device_last_detected_temperature" , Long.class );
	public static final DBColumn SENSOR2 =  new DefaultDBColumn( table , "sensor2" , Long.class );
	public static final DBColumn SENSOR3 =  new DefaultDBColumn( table , "sensor3" , Long.class );
	public static final DBColumn SENSOR4 =  new DefaultDBColumn( table , "sensor4" , Long.class );
	public static final DBColumn SENSOR5 =  new DefaultDBColumn( table , "sensor5" , Long.class );
	public static final DBColumn SENSOR6 =  new DefaultDBColumn( table , "sensor6" , Long.class );
	public static final DBColumn SENSOR7 =  new DefaultDBColumn( table , "sensor7" , Long.class );
	public static final DBColumn SENSOR8 =  new DefaultDBColumn( table , "sensor8" , Long.class );
	public static final DBColumn SENSOR1 =  new DefaultDBColumn( table , "sensor1" , Long.class );
	public static final DBColumn STATUS_DESCRIPTION =  new DefaultDBColumn( table , "status_description" , String.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[42];
		array[0] = ID;
		array[1] = EXTERNAL_ID;
		array[2] = NAME;
		array[3] = EXTERNAL_NAME;
		array[4] = UP_ID;
		array[5] = KM;
		array[6] = LOCAL;
		array[7] = LAST_DATA_DATE;
		array[8] = LAST_ACTIVATION_DATE;
		array[9] = CREATION_DATE;
		array[10] = UPDATE_DATE;
		array[11] = INPUT1;
		array[12] = INPUT2;
		array[13] = INPUT3;
		array[14] = INPUT4;
		array[15] = INPUT5;
		array[16] = INPUT6;
		array[17] = OUTPUT;
		array[18] = VOLTAGE;
		array[19] = CELL_LEVEL;
		array[20] = LATITUDE;
		array[21] = LONGITUDE;
		array[22] = STATUS;
		array[23] = DELETED;
		array[24] = VOLTAGE_SLAVE;
		array[25] = TYPE;
		array[26] = PN_TYPE;
		array[27] = DEVICE_LAST_DETECTED_SPEED;
		array[28] = DEVICE_LAST_NUMBER_OF_EIXOS;
		array[29] = DEVICE_LAST_DETECTED_WEIGHT;
		array[30] = LAST_DETECTION_START_DATE;
		array[31] = LAST_DETECTION_END_DATE;
		array[32] = DEVICE_LAST_DETECTED_TEMPERATURE;
		array[33] = SENSOR2;
		array[34] = SENSOR3;
		array[35] = SENSOR4;
		array[36] = SENSOR5;
		array[37] = SENSOR6;
		array[38] = SENSOR7;
		array[39] = SENSOR8;
		array[40] = SENSOR1;
		array[41] = STATUS_DESCRIPTION;
		return array;
	}
}
