// class generated by JConcept Database ClassBuilder 2.0
package com.mycompany.dbmapping;

// import JConcept Database library
import br.com.jconcept.database.*;

import br.com.jconcept.database.query.*;

import java.util.Date;

import java.math.BigDecimal;

public class ClientDBHelper{
	public static final DBTable table = new DefaultDBTable("CLIENT");

	public static final DBColumn CLIENT_ID =  new DefaultDBColumn( table , "CLIENT_ID" , Long.class );
	public static final DBColumn NAME =  new DefaultDBColumn( table , "NAME" , String.class );
	public static final DBColumn LAST_NAME =  new DefaultDBColumn( table , "LAST_NAME" , String.class );
	public static final DBColumn BIRTH_DATE =  new DefaultDBColumn( table , "BIRTH_DATE" , Date.class );
	public static final DBColumn STREET =  new DefaultDBColumn( table , "STREET" , String.class );
	public static final DBColumn STREET_NUMBER =  new DefaultDBColumn( table , "STREET_NUMBER" , Long.class );
	public static final DBColumn DEBIT =  new DefaultDBColumn( table , "DEBIT" , Double.class );
	public static final DBColumn CREDIT =  new DefaultDBColumn( table , "CREDIT" , Double.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[8];
		array[0] = CLIENT_ID;
		array[1] = NAME;
		array[2] = LAST_NAME;
		array[3] = BIRTH_DATE;
		array[4] = STREET;
		array[5] = STREET_NUMBER;
		array[6] = DEBIT;
		array[7] = CREDIT;
		return array;
	}
}
