// class generated by JConcept Database ClassBuilder 2.0
package com.mycompany.myobjects;

// import JConcept Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import org.neodatis.rdb.implementation.*;

// For Date attribute
import java.util.Date;

// For BigDecimal attribute
import java.math.*;

public class ControlePraca extends Object  implements DbObjectMapping 
{
	//** Database fields
	protected Long dbID;
	protected Long dbID_PRACA;
	protected String dbNOME_PRACA;
	protected Date dbDATA_HORA_ULTIMA_COMUNICACAO;
	protected String dbDESCRICAO_MSG;

	//** Construtor
	public ControlePraca()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("ID");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("CONTROLE_COMUNICACAO_PRACA");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbID = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbID;
	}

	// Setter for attribute idPraca
	public void setIdPraca( Long in_idPraca ) 
	{
		dbID_PRACA = in_idPraca;
	}

	// Getter for attribute idPraca
	public Long getIdPraca()
	{
		return dbID_PRACA;
	}

	// Setter for attribute nomePraca
	public void setNomePraca( String in_nomePraca ) 
	{
		dbNOME_PRACA = in_nomePraca;
	}

	// Getter for attribute nomePraca
	public String getNomePraca()
	{
		return dbNOME_PRACA;
	}

	// Setter for attribute dataHoraUltimaComunicacao
	public void setDataHoraUltimaComunicacao( Date in_dataHoraUltimaComunicacao ) 
	{
		dbDATA_HORA_ULTIMA_COMUNICACAO = in_dataHoraUltimaComunicacao;
	}

	// Getter for attribute dataHoraUltimaComunicacao
	public Date getDataHoraUltimaComunicacao()
	{
		return dbDATA_HORA_ULTIMA_COMUNICACAO;
	}

	// Setter for attribute descricaoMsg
	public void setDescricaoMsg( String in_descricaoMsg ) 
	{
		dbDESCRICAO_MSG = in_descricaoMsg;
	}

	// Getter for attribute descricaoMsg
	public String getDescricaoMsg()
	{
		return dbDESCRICAO_MSG;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t idPraca : " ).append( getIdPraca()).append("\n");
		sResult.append( "\t nomePraca : " ).append( getNomePraca()).append("\n");
		sResult.append( "\t dataHoraUltimaComunicacao : " ).append( getDataHoraUltimaComunicacao()).append("\n");
		sResult.append( "\t descricaoMsg : " ).append( getDescricaoMsg()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

}
	//** Database fields
