// class generated by JConcept Database ClassBuilder 2.0
package com.mycompany.myobjects;

// import JConcept Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import org.neodatis.rdb.implementation.*;

// For Date attribute
import java.util.Date;

// For BigDecimal attribute
import java.math.*;

public class TransferenciaArquivo extends Object  implements DbObjectMapping 
{
	//** Database fields
	protected Long dbID;
	protected Date dbDATA_HORA_INICIO_TRANSFERENCIA;
	protected String dbNOME_DIRETORIO_ORIGINAL;
	protected String dbNOME_ARQUIVO_ORIGINAL;
	protected String dbNOME_ARQUIVO_FORNECEDOR;
	protected Long dbTAMANHO_ARQUIVO_ORIGINAL;
	protected Long dbCRC_ORIGEM;
	protected Date dbDATA_HORA_FIM_TRANSFERENCIA;
	protected String dbNOME_DIRETORIO_DESTINO;
	protected String dbNOME_ARQUIVO_DESTINO;
	protected Long dbTAMANHO_ARQUIVO_DESTINO;
	protected Long dbCRC_DESTINO;
	protected Long dbTRANSFERENCIA_OK;
	protected Long dbESTADO;
	protected Date dbDATA_HORA_PROCESSAMENTO;
	protected Long dbDURACAO_PROCESSAMENTO_MS;
	protected Long dbNUMERO_TRANSACOES;
	protected Long dbNUMERO_ALERTAS;
	protected Long dbID_PRACA;

	//** Construtor
	public TransferenciaArquivo()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("ID");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("TRANSFERENCIA_ARQUIVO");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbID = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbID;
	}

	// Setter for attribute dataHoraInicioTransferencia
	public void setDataHoraInicioTransferencia( Date in_dataHoraInicioTransferencia ) 
	{
		dbDATA_HORA_INICIO_TRANSFERENCIA = in_dataHoraInicioTransferencia;
	}

	// Getter for attribute dataHoraInicioTransferencia
	public Date getDataHoraInicioTransferencia()
	{
		return dbDATA_HORA_INICIO_TRANSFERENCIA;
	}

	// Setter for attribute nomeDiretorioOriginal
	public void setNomeDiretorioOriginal( String in_nomeDiretorioOriginal ) 
	{
		dbNOME_DIRETORIO_ORIGINAL = in_nomeDiretorioOriginal;
	}

	// Getter for attribute nomeDiretorioOriginal
	public String getNomeDiretorioOriginal()
	{
		return dbNOME_DIRETORIO_ORIGINAL;
	}

	// Setter for attribute nomeArquivoOriginal
	public void setNomeArquivoOriginal( String in_nomeArquivoOriginal ) 
	{
		dbNOME_ARQUIVO_ORIGINAL = in_nomeArquivoOriginal;
	}

	// Getter for attribute nomeArquivoOriginal
	public String getNomeArquivoOriginal()
	{
		return dbNOME_ARQUIVO_ORIGINAL;
	}

	// Setter for attribute nomeArquivoFornecedor
	public void setNomeArquivoFornecedor( String in_nomeArquivoFornecedor ) 
	{
		dbNOME_ARQUIVO_FORNECEDOR = in_nomeArquivoFornecedor;
	}

	// Getter for attribute nomeArquivoFornecedor
	public String getNomeArquivoFornecedor()
	{
		return dbNOME_ARQUIVO_FORNECEDOR;
	}

	// Setter for attribute tamanhoArquivoOriginal
	public void setTamanhoArquivoOriginal( Long in_tamanhoArquivoOriginal ) 
	{
		dbTAMANHO_ARQUIVO_ORIGINAL = in_tamanhoArquivoOriginal;
	}

	// Getter for attribute tamanhoArquivoOriginal
	public Long getTamanhoArquivoOriginal()
	{
		return dbTAMANHO_ARQUIVO_ORIGINAL;
	}

	// Setter for attribute crcOrigem
	public void setCrcOrigem( Long in_crcOrigem ) 
	{
		dbCRC_ORIGEM = in_crcOrigem;
	}

	// Getter for attribute crcOrigem
	public Long getCrcOrigem()
	{
		return dbCRC_ORIGEM;
	}

	// Setter for attribute dataHoraFimTransferencia
	public void setDataHoraFimTransferencia( Date in_dataHoraFimTransferencia ) 
	{
		dbDATA_HORA_FIM_TRANSFERENCIA = in_dataHoraFimTransferencia;
	}

	// Getter for attribute dataHoraFimTransferencia
	public Date getDataHoraFimTransferencia()
	{
		return dbDATA_HORA_FIM_TRANSFERENCIA;
	}

	// Setter for attribute nomeDiretorioDestino
	public void setNomeDiretorioDestino( String in_nomeDiretorioDestino ) 
	{
		dbNOME_DIRETORIO_DESTINO = in_nomeDiretorioDestino;
	}

	// Getter for attribute nomeDiretorioDestino
	public String getNomeDiretorioDestino()
	{
		return dbNOME_DIRETORIO_DESTINO;
	}

	// Setter for attribute nomeArquivoDestino
	public void setNomeArquivoDestino( String in_nomeArquivoDestino ) 
	{
		dbNOME_ARQUIVO_DESTINO = in_nomeArquivoDestino;
	}

	// Getter for attribute nomeArquivoDestino
	public String getNomeArquivoDestino()
	{
		return dbNOME_ARQUIVO_DESTINO;
	}

	// Setter for attribute tamanhoArquivoDestino
	public void setTamanhoArquivoDestino( Long in_tamanhoArquivoDestino ) 
	{
		dbTAMANHO_ARQUIVO_DESTINO = in_tamanhoArquivoDestino;
	}

	// Getter for attribute tamanhoArquivoDestino
	public Long getTamanhoArquivoDestino()
	{
		return dbTAMANHO_ARQUIVO_DESTINO;
	}

	// Setter for attribute crcDestino
	public void setCrcDestino( Long in_crcDestino ) 
	{
		dbCRC_DESTINO = in_crcDestino;
	}

	// Getter for attribute crcDestino
	public Long getCrcDestino()
	{
		return dbCRC_DESTINO;
	}

	// Setter for attribute transferenciaOk
	public void setTransferenciaOk( Long in_transferenciaOk ) 
	{
		dbTRANSFERENCIA_OK = in_transferenciaOk;
	}

	// Getter for attribute transferenciaOk
	public Long getTransferenciaOk()
	{
		return dbTRANSFERENCIA_OK;
	}

	// Setter for attribute estado
	public void setEstado( Long in_estado ) 
	{
		dbESTADO = in_estado;
	}

	// Getter for attribute estado
	public Long getEstado()
	{
		return dbESTADO;
	}

	// Setter for attribute dataHoraProcessamento
	public void setDataHoraProcessamento( Date in_dataHoraProcessamento ) 
	{
		dbDATA_HORA_PROCESSAMENTO = in_dataHoraProcessamento;
	}

	// Getter for attribute dataHoraProcessamento
	public Date getDataHoraProcessamento()
	{
		return dbDATA_HORA_PROCESSAMENTO;
	}

	// Setter for attribute duracaoProcessamentoMs
	public void setDuracaoProcessamentoMs( Long in_duracaoProcessamentoMs ) 
	{
		dbDURACAO_PROCESSAMENTO_MS = in_duracaoProcessamentoMs;
	}

	// Getter for attribute duracaoProcessamentoMs
	public Long getDuracaoProcessamentoMs()
	{
		return dbDURACAO_PROCESSAMENTO_MS;
	}

	// Setter for attribute numeroTransacoes
	public void setNumeroTransacoes( Long in_numeroTransacoes ) 
	{
		dbNUMERO_TRANSACOES = in_numeroTransacoes;
	}

	// Getter for attribute numeroTransacoes
	public Long getNumeroTransacoes()
	{
		return dbNUMERO_TRANSACOES;
	}

	// Setter for attribute numeroAlertas
	public void setNumeroAlertas( Long in_numeroAlertas ) 
	{
		dbNUMERO_ALERTAS = in_numeroAlertas;
	}

	// Getter for attribute numeroAlertas
	public Long getNumeroAlertas()
	{
		return dbNUMERO_ALERTAS;
	}

	// Setter for attribute idPraca
	public void setIdPraca( Long in_idPraca ) 
	{
		dbID_PRACA = in_idPraca;
	}

	// Getter for attribute idPraca
	public Long getIdPraca()
	{
		return dbID_PRACA;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t dataHoraInicioTransferencia : " ).append( getDataHoraInicioTransferencia()).append("\n");
		sResult.append( "\t nomeDiretorioOriginal : " ).append( getNomeDiretorioOriginal()).append("\n");
		sResult.append( "\t nomeArquivoOriginal : " ).append( getNomeArquivoOriginal()).append("\n");
		sResult.append( "\t nomeArquivoFornecedor : " ).append( getNomeArquivoFornecedor()).append("\n");
		sResult.append( "\t tamanhoArquivoOriginal : " ).append( getTamanhoArquivoOriginal()).append("\n");
		sResult.append( "\t crcOrigem : " ).append( getCrcOrigem()).append("\n");
		sResult.append( "\t dataHoraFimTransferencia : " ).append( getDataHoraFimTransferencia()).append("\n");
		sResult.append( "\t nomeDiretorioDestino : " ).append( getNomeDiretorioDestino()).append("\n");
		sResult.append( "\t nomeArquivoDestino : " ).append( getNomeArquivoDestino()).append("\n");
		sResult.append( "\t tamanhoArquivoDestino : " ).append( getTamanhoArquivoDestino()).append("\n");
		sResult.append( "\t crcDestino : " ).append( getCrcDestino()).append("\n");
		sResult.append( "\t transferenciaOk : " ).append( getTransferenciaOk()).append("\n");
		sResult.append( "\t estado : " ).append( getEstado()).append("\n");
		sResult.append( "\t dataHoraProcessamento : " ).append( getDataHoraProcessamento()).append("\n");
		sResult.append( "\t duracaoProcessamentoMs : " ).append( getDuracaoProcessamentoMs()).append("\n");
		sResult.append( "\t numeroTransacoes : " ).append( getNumeroTransacoes()).append("\n");
		sResult.append( "\t numeroAlertas : " ).append( getNumeroAlertas()).append("\n");
		sResult.append( "\t idPraca : " ).append( getIdPraca()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

}
	//** Database fields
