// class generated by JConcept Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model;

// import JConcept Database library
import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.DbObjectMapping;
import org.neodatis.rdb.PrimaryKey;
import org.neodatis.rdb.Service;
import org.neodatis.rdb.implementation.DefaultPrimaryKey;
import org.neodatis.rdb.query.DefaultDBTable;
// For Date attribute
// For BigDecimal attribute

public class Company extends org.neodatis.rdb.DbObjectWithLongId  implements DbObjectMapping , org.neodatis.rdb.ToX
 ,java.io.Serializable
{
	//** Database fields
	protected Long dbid;
	protected String dbname;
	protected Long dbstatus;
	protected Long dbdeleted;
	//** Db Object
	public static Service<Company> DB = new Service<Company>(Company.class);

	//** Construtor
	public Company()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("id");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("company");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbid = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbid;
	}

	// Setter for attribute name
	public void setName( String in_name ) 
	{
		dbname = in_name;
	}

	// Getter for attribute name
	public String getName()
	{
		return dbname;
	}

	// Setter for attribute status
	public void setStatus( Long in_status ) 
	{
		dbstatus = in_status;
	}

	// Getter for attribute status
	public Long getStatus()
	{
		return dbstatus;
	}

	// Setter for attribute deleted
	public void setDeleted( Long in_deleted ) 
	{
		dbdeleted = in_deleted;
	}

	// Getter for attribute deleted
	public Long getDeleted()
	{
		return dbdeleted;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t name : " ).append( getName()).append("\n");
		sResult.append( "\t status : " ).append( getStatus()).append("\n");
		sResult.append( "\t deleted : " ).append( getDeleted()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

	/** toMap method*/
	public java.util.Map<String,Object> toMap()
	{

		java.util.Map<String,Object> map = new java.util.HashMap<String,Object>();
		map.put( "id" , String.valueOf(getId()));
		map.put( "name" , String.valueOf(getName()));
		map.put( "status" , String.valueOf(getStatus()));
		map.put( "deleted" , String.valueOf(getDeleted()));
		return map;
	}

	/** toJSon method*/
	public String toJSon()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("{");
		sResult.append( "\"id\":\"" ).append(String.valueOf(getId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"name\":\"" ).append(String.valueOf(getName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"status\":\"" ).append(String.valueOf(getStatus()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deleted\":\"" ).append(String.valueOf(getDeleted()) ).append("\"");
		sResult.append("}");
		return sResult.toString();
	}

	/** toList method*/
	public java.util.List<String> toList()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( String.valueOf(getId()));
		list.add( String.valueOf(getName()));
		list.add( String.valueOf(getStatus()));
		list.add( String.valueOf(getDeleted()));
		return list;
	}

	/** getAttributeNames method*/
	public java.util.List<String> getAttributeNames()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( "id");
		list.add( "name");
		list.add( "status");
		list.add( "deleted");
		return list;
	}

}
	//** Database fields
