// class generated by JConcept Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model;

// import JConcept Database library
// For BigDecimal attribute
import java.math.BigDecimal;
// For Date attribute
import java.util.Date;

import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.DbObjectMapping;
import org.neodatis.rdb.PrimaryKey;
import org.neodatis.rdb.Service;
import org.neodatis.rdb.implementation.DefaultPrimaryKey;
import org.neodatis.rdb.query.DefaultDBTable;

public class Pn extends org.neodatis.rdb.DbObjectWithLongId  implements DbObjectMapping , org.neodatis.rdb.ToX
 ,java.io.Serializable
{
	//** Database fields
	protected Long dbid;
	protected Long dbexternal_id;
	protected String dbname;
	protected String dbexternal_name;
	protected Long dbup_id;
	protected BigDecimal dbkm;
	protected String dblocal;
	protected Date dblast_data_date;
	protected Date dblast_activation_date;
	protected Date dbcreation_date;
	protected Date dbupdate_date;
	protected Long dbinput1;
	protected Long dbinput2;
	protected Long dbinput3;
	protected Long dbinput4;
	protected Long dbinput5;
	protected Long dbinput6;
	protected Long dboutput;
	protected BigDecimal dbvoltage;
	protected BigDecimal dbcell_level;
	protected BigDecimal dblatitude;
	protected BigDecimal dblongitude;
	protected Long dbstatus;
	protected Long dbdeleted;
	protected BigDecimal dbvoltage_slave;
	protected Long dbtype;
	protected Long dbpn_type;
	protected BigDecimal dbdevice_last_detected_speed;
	protected Long dbdevice_last_number_of_eixos;
	protected BigDecimal dbdevice_last_detected_weight;
	protected Date dblast_detection_start_date;
	protected Date dblast_detection_end_date;
	protected Long dbdevice_last_detected_temperature;
	protected Long dbsensor2;
	protected Long dbsensor3;
	protected Long dbsensor4;
	protected Long dbsensor5;
	protected Long dbsensor6;
	protected Long dbsensor7;
	protected Long dbsensor8;
	protected Long dbsensor1;
	protected String dbstatus_description;
	//** Db Object
	public static Service<Pn> DB = new Service<Pn>(Pn.class);

	//** Construtor
	public Pn()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("id");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("pn");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbid = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbid;
	}

	// Setter for attribute externalId
	public void setExternalId( Long in_externalId ) 
	{
		dbexternal_id = in_externalId;
	}

	// Getter for attribute externalId
	public Long getExternalId()
	{
		return dbexternal_id;
	}

	// Setter for attribute name
	public void setName( String in_name ) 
	{
		dbname = in_name;
	}

	// Getter for attribute name
	public String getName()
	{
		return dbname;
	}

	// Setter for attribute externalName
	public void setExternalName( String in_externalName ) 
	{
		dbexternal_name = in_externalName;
	}

	// Getter for attribute externalName
	public String getExternalName()
	{
		return dbexternal_name;
	}

	// Setter for attribute upId
	public void setUpId( Long in_upId ) 
	{
		dbup_id = in_upId;
	}

	// Getter for attribute upId
	public Long getUpId()
	{
		return dbup_id;
	}

	// Setter for attribute km
	public void setKm( BigDecimal in_km ) 
	{
		dbkm = in_km;
	}

	// Getter for attribute km
	public BigDecimal getKm()
	{
		return dbkm;
	}

	// Setter for attribute local
	public void setLocal( String in_local ) 
	{
		dblocal = in_local;
	}

	// Getter for attribute local
	public String getLocal()
	{
		return dblocal;
	}

	// Setter for attribute lastDataDate
	public void setLastDataDate( Date in_lastDataDate ) 
	{
		dblast_data_date = in_lastDataDate;
	}

	// Getter for attribute lastDataDate
	public Date getLastDataDate()
	{
		return dblast_data_date;
	}

	// Setter for attribute lastActivationDate
	public void setLastActivationDate( Date in_lastActivationDate ) 
	{
		dblast_activation_date = in_lastActivationDate;
	}

	// Getter for attribute lastActivationDate
	public Date getLastActivationDate()
	{
		return dblast_activation_date;
	}

	// Setter for attribute creationDate
	public void setCreationDate( Date in_creationDate ) 
	{
		dbcreation_date = in_creationDate;
	}

	// Getter for attribute creationDate
	public Date getCreationDate()
	{
		return dbcreation_date;
	}

	// Setter for attribute updateDate
	public void setUpdateDate( Date in_updateDate ) 
	{
		dbupdate_date = in_updateDate;
	}

	// Getter for attribute updateDate
	public Date getUpdateDate()
	{
		return dbupdate_date;
	}

	// Setter for attribute input1
	public void setInput1( Long in_input1 ) 
	{
		dbinput1 = in_input1;
	}

	// Getter for attribute input1
	public Long getInput1()
	{
		return dbinput1;
	}

	// Setter for attribute input2
	public void setInput2( Long in_input2 ) 
	{
		dbinput2 = in_input2;
	}

	// Getter for attribute input2
	public Long getInput2()
	{
		return dbinput2;
	}

	// Setter for attribute input3
	public void setInput3( Long in_input3 ) 
	{
		dbinput3 = in_input3;
	}

	// Getter for attribute input3
	public Long getInput3()
	{
		return dbinput3;
	}

	// Setter for attribute input4
	public void setInput4( Long in_input4 ) 
	{
		dbinput4 = in_input4;
	}

	// Getter for attribute input4
	public Long getInput4()
	{
		return dbinput4;
	}

	// Setter for attribute input5
	public void setInput5( Long in_input5 ) 
	{
		dbinput5 = in_input5;
	}

	// Getter for attribute input5
	public Long getInput5()
	{
		return dbinput5;
	}

	// Setter for attribute input6
	public void setInput6( Long in_input6 ) 
	{
		dbinput6 = in_input6;
	}

	// Getter for attribute input6
	public Long getInput6()
	{
		return dbinput6;
	}

	// Setter for attribute output
	public void setOutput( Long in_output ) 
	{
		dboutput = in_output;
	}

	// Getter for attribute output
	public Long getOutput()
	{
		return dboutput;
	}

	// Setter for attribute voltage
	public void setVoltage( BigDecimal in_voltage ) 
	{
		dbvoltage = in_voltage;
	}

	// Getter for attribute voltage
	public BigDecimal getVoltage()
	{
		return dbvoltage;
	}

	// Setter for attribute cellLevel
	public void setCellLevel( BigDecimal in_cellLevel ) 
	{
		dbcell_level = in_cellLevel;
	}

	// Getter for attribute cellLevel
	public BigDecimal getCellLevel()
	{
		return dbcell_level;
	}

	// Setter for attribute latitude
	public void setLatitude( BigDecimal in_latitude ) 
	{
		dblatitude = in_latitude;
	}

	// Getter for attribute latitude
	public BigDecimal getLatitude()
	{
		return dblatitude;
	}

	// Setter for attribute longitude
	public void setLongitude( BigDecimal in_longitude ) 
	{
		dblongitude = in_longitude;
	}

	// Getter for attribute longitude
	public BigDecimal getLongitude()
	{
		return dblongitude;
	}

	// Setter for attribute status
	public void setStatus( Long in_status ) 
	{
		dbstatus = in_status;
	}

	// Getter for attribute status
	public Long getStatus()
	{
		return dbstatus;
	}

	// Setter for attribute deleted
	public void setDeleted( Long in_deleted ) 
	{
		dbdeleted = in_deleted;
	}

	// Getter for attribute deleted
	public Long getDeleted()
	{
		return dbdeleted;
	}

	// Setter for attribute voltageSlave
	public void setVoltageSlave( BigDecimal in_voltageSlave ) 
	{
		dbvoltage_slave = in_voltageSlave;
	}

	// Getter for attribute voltageSlave
	public BigDecimal getVoltageSlave()
	{
		return dbvoltage_slave;
	}

	// Setter for attribute type
	public void setType( Long in_type ) 
	{
		dbtype = in_type;
	}

	// Getter for attribute type
	public Long getType()
	{
		return dbtype;
	}

	// Setter for attribute pnType
	public void setPnType( Long in_pnType ) 
	{
		dbpn_type = in_pnType;
	}

	// Getter for attribute pnType
	public Long getPnType()
	{
		return dbpn_type;
	}

	// Setter for attribute deviceLastDetectedSpeed
	public void setDeviceLastDetectedSpeed( BigDecimal in_deviceLastDetectedSpeed ) 
	{
		dbdevice_last_detected_speed = in_deviceLastDetectedSpeed;
	}

	// Getter for attribute deviceLastDetectedSpeed
	public BigDecimal getDeviceLastDetectedSpeed()
	{
		return dbdevice_last_detected_speed;
	}

	// Setter for attribute deviceLastNumberOfEixos
	public void setDeviceLastNumberOfEixos( Long in_deviceLastNumberOfEixos ) 
	{
		dbdevice_last_number_of_eixos = in_deviceLastNumberOfEixos;
	}

	// Getter for attribute deviceLastNumberOfEixos
	public Long getDeviceLastNumberOfEixos()
	{
		return dbdevice_last_number_of_eixos;
	}

	// Setter for attribute deviceLastDetectedWeight
	public void setDeviceLastDetectedWeight( BigDecimal in_deviceLastDetectedWeight ) 
	{
		dbdevice_last_detected_weight = in_deviceLastDetectedWeight;
	}

	// Getter for attribute deviceLastDetectedWeight
	public BigDecimal getDeviceLastDetectedWeight()
	{
		return dbdevice_last_detected_weight;
	}

	// Setter for attribute lastDetectionStartDate
	public void setLastDetectionStartDate( Date in_lastDetectionStartDate ) 
	{
		dblast_detection_start_date = in_lastDetectionStartDate;
	}

	// Getter for attribute lastDetectionStartDate
	public Date getLastDetectionStartDate()
	{
		return dblast_detection_start_date;
	}

	// Setter for attribute lastDetectionEndDate
	public void setLastDetectionEndDate( Date in_lastDetectionEndDate ) 
	{
		dblast_detection_end_date = in_lastDetectionEndDate;
	}

	// Getter for attribute lastDetectionEndDate
	public Date getLastDetectionEndDate()
	{
		return dblast_detection_end_date;
	}

	// Setter for attribute deviceLastDetectedTemperature
	public void setDeviceLastDetectedTemperature( Long in_deviceLastDetectedTemperature ) 
	{
		dbdevice_last_detected_temperature = in_deviceLastDetectedTemperature;
	}

	// Getter for attribute deviceLastDetectedTemperature
	public Long getDeviceLastDetectedTemperature()
	{
		return dbdevice_last_detected_temperature;
	}

	// Setter for attribute sensor2
	public void setSensor2( Long in_sensor2 ) 
	{
		dbsensor2 = in_sensor2;
	}

	// Getter for attribute sensor2
	public Long getSensor2()
	{
		return dbsensor2;
	}

	// Setter for attribute sensor3
	public void setSensor3( Long in_sensor3 ) 
	{
		dbsensor3 = in_sensor3;
	}

	// Getter for attribute sensor3
	public Long getSensor3()
	{
		return dbsensor3;
	}

	// Setter for attribute sensor4
	public void setSensor4( Long in_sensor4 ) 
	{
		dbsensor4 = in_sensor4;
	}

	// Getter for attribute sensor4
	public Long getSensor4()
	{
		return dbsensor4;
	}

	// Setter for attribute sensor5
	public void setSensor5( Long in_sensor5 ) 
	{
		dbsensor5 = in_sensor5;
	}

	// Getter for attribute sensor5
	public Long getSensor5()
	{
		return dbsensor5;
	}

	// Setter for attribute sensor6
	public void setSensor6( Long in_sensor6 ) 
	{
		dbsensor6 = in_sensor6;
	}

	// Getter for attribute sensor6
	public Long getSensor6()
	{
		return dbsensor6;
	}

	// Setter for attribute sensor7
	public void setSensor7( Long in_sensor7 ) 
	{
		dbsensor7 = in_sensor7;
	}

	// Getter for attribute sensor7
	public Long getSensor7()
	{
		return dbsensor7;
	}

	// Setter for attribute sensor8
	public void setSensor8( Long in_sensor8 ) 
	{
		dbsensor8 = in_sensor8;
	}

	// Getter for attribute sensor8
	public Long getSensor8()
	{
		return dbsensor8;
	}

	// Setter for attribute sensor1
	public void setSensor1( Long in_sensor1 ) 
	{
		dbsensor1 = in_sensor1;
	}

	// Getter for attribute sensor1
	public Long getSensor1()
	{
		return dbsensor1;
	}

	// Setter for attribute statusDescription
	public void setStatusDescription( String in_statusDescription ) 
	{
		dbstatus_description = in_statusDescription;
	}

	// Getter for attribute statusDescription
	public String getStatusDescription()
	{
		return dbstatus_description;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t externalId : " ).append( getExternalId()).append("\n");
		sResult.append( "\t name : " ).append( getName()).append("\n");
		sResult.append( "\t externalName : " ).append( getExternalName()).append("\n");
		sResult.append( "\t upId : " ).append( getUpId()).append("\n");
		sResult.append( "\t km : " ).append( getKm()).append("\n");
		sResult.append( "\t local : " ).append( getLocal()).append("\n");
		sResult.append( "\t lastDataDate : " ).append( getLastDataDate()).append("\n");
		sResult.append( "\t lastActivationDate : " ).append( getLastActivationDate()).append("\n");
		sResult.append( "\t creationDate : " ).append( getCreationDate()).append("\n");
		sResult.append( "\t updateDate : " ).append( getUpdateDate()).append("\n");
		sResult.append( "\t input1 : " ).append( getInput1()).append("\n");
		sResult.append( "\t input2 : " ).append( getInput2()).append("\n");
		sResult.append( "\t input3 : " ).append( getInput3()).append("\n");
		sResult.append( "\t input4 : " ).append( getInput4()).append("\n");
		sResult.append( "\t input5 : " ).append( getInput5()).append("\n");
		sResult.append( "\t input6 : " ).append( getInput6()).append("\n");
		sResult.append( "\t output : " ).append( getOutput()).append("\n");
		sResult.append( "\t voltage : " ).append( getVoltage()).append("\n");
		sResult.append( "\t cellLevel : " ).append( getCellLevel()).append("\n");
		sResult.append( "\t latitude : " ).append( getLatitude()).append("\n");
		sResult.append( "\t longitude : " ).append( getLongitude()).append("\n");
		sResult.append( "\t status : " ).append( getStatus()).append("\n");
		sResult.append( "\t deleted : " ).append( getDeleted()).append("\n");
		sResult.append( "\t voltageSlave : " ).append( getVoltageSlave()).append("\n");
		sResult.append( "\t type : " ).append( getType()).append("\n");
		sResult.append( "\t pnType : " ).append( getPnType()).append("\n");
		sResult.append( "\t deviceLastDetectedSpeed : " ).append( getDeviceLastDetectedSpeed()).append("\n");
		sResult.append( "\t deviceLastNumberOfEixos : " ).append( getDeviceLastNumberOfEixos()).append("\n");
		sResult.append( "\t deviceLastDetectedWeight : " ).append( getDeviceLastDetectedWeight()).append("\n");
		sResult.append( "\t lastDetectionStartDate : " ).append( getLastDetectionStartDate()).append("\n");
		sResult.append( "\t lastDetectionEndDate : " ).append( getLastDetectionEndDate()).append("\n");
		sResult.append( "\t deviceLastDetectedTemperature : " ).append( getDeviceLastDetectedTemperature()).append("\n");
		sResult.append( "\t sensor2 : " ).append( getSensor2()).append("\n");
		sResult.append( "\t sensor3 : " ).append( getSensor3()).append("\n");
		sResult.append( "\t sensor4 : " ).append( getSensor4()).append("\n");
		sResult.append( "\t sensor5 : " ).append( getSensor5()).append("\n");
		sResult.append( "\t sensor6 : " ).append( getSensor6()).append("\n");
		sResult.append( "\t sensor7 : " ).append( getSensor7()).append("\n");
		sResult.append( "\t sensor8 : " ).append( getSensor8()).append("\n");
		sResult.append( "\t sensor1 : " ).append( getSensor1()).append("\n");
		sResult.append( "\t statusDescription : " ).append( getStatusDescription()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

	/** toMap method*/
	public java.util.Map<String,Object> toMap()
	{

		java.util.Map<String,Object> map = new java.util.HashMap<String,Object>();
		map.put( "id" , String.valueOf(getId()));
		map.put( "externalId" , String.valueOf(getExternalId()));
		map.put( "name" , String.valueOf(getName()));
		map.put( "externalName" , String.valueOf(getExternalName()));
		map.put( "upId" , String.valueOf(getUpId()));
		map.put( "km" , String.valueOf(getKm()));
		map.put( "local" , String.valueOf(getLocal()));
		map.put( "lastDataDate" , String.valueOf(getLastDataDate()));
		map.put( "lastActivationDate" , String.valueOf(getLastActivationDate()));
		map.put( "creationDate" , String.valueOf(getCreationDate()));
		map.put( "updateDate" , String.valueOf(getUpdateDate()));
		map.put( "input1" , String.valueOf(getInput1()));
		map.put( "input2" , String.valueOf(getInput2()));
		map.put( "input3" , String.valueOf(getInput3()));
		map.put( "input4" , String.valueOf(getInput4()));
		map.put( "input5" , String.valueOf(getInput5()));
		map.put( "input6" , String.valueOf(getInput6()));
		map.put( "output" , String.valueOf(getOutput()));
		map.put( "voltage" , String.valueOf(getVoltage()));
		map.put( "cellLevel" , String.valueOf(getCellLevel()));
		map.put( "latitude" , String.valueOf(getLatitude()));
		map.put( "longitude" , String.valueOf(getLongitude()));
		map.put( "status" , String.valueOf(getStatus()));
		map.put( "deleted" , String.valueOf(getDeleted()));
		map.put( "voltageSlave" , String.valueOf(getVoltageSlave()));
		map.put( "type" , String.valueOf(getType()));
		map.put( "pnType" , String.valueOf(getPnType()));
		map.put( "deviceLastDetectedSpeed" , String.valueOf(getDeviceLastDetectedSpeed()));
		map.put( "deviceLastNumberOfEixos" , String.valueOf(getDeviceLastNumberOfEixos()));
		map.put( "deviceLastDetectedWeight" , String.valueOf(getDeviceLastDetectedWeight()));
		map.put( "lastDetectionStartDate" , String.valueOf(getLastDetectionStartDate()));
		map.put( "lastDetectionEndDate" , String.valueOf(getLastDetectionEndDate()));
		map.put( "deviceLastDetectedTemperature" , String.valueOf(getDeviceLastDetectedTemperature()));
		map.put( "sensor2" , String.valueOf(getSensor2()));
		map.put( "sensor3" , String.valueOf(getSensor3()));
		map.put( "sensor4" , String.valueOf(getSensor4()));
		map.put( "sensor5" , String.valueOf(getSensor5()));
		map.put( "sensor6" , String.valueOf(getSensor6()));
		map.put( "sensor7" , String.valueOf(getSensor7()));
		map.put( "sensor8" , String.valueOf(getSensor8()));
		map.put( "sensor1" , String.valueOf(getSensor1()));
		map.put( "statusDescription" , String.valueOf(getStatusDescription()));
		return map;
	}

	/** toJSon method*/
	public String toJSon()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("{");
		sResult.append( "\"id\":\"" ).append(String.valueOf(getId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"externalId\":\"" ).append(String.valueOf(getExternalId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"name\":\"" ).append(String.valueOf(getName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"externalName\":\"" ).append(String.valueOf(getExternalName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"upId\":\"" ).append(String.valueOf(getUpId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"km\":\"" ).append(String.valueOf(getKm()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"local\":\"" ).append(String.valueOf(getLocal()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastDataDate\":\"" ).append(String.valueOf(getLastDataDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastActivationDate\":\"" ).append(String.valueOf(getLastActivationDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"creationDate\":\"" ).append(String.valueOf(getCreationDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"updateDate\":\"" ).append(String.valueOf(getUpdateDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input1\":\"" ).append(String.valueOf(getInput1()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input2\":\"" ).append(String.valueOf(getInput2()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input3\":\"" ).append(String.valueOf(getInput3()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input4\":\"" ).append(String.valueOf(getInput4()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input5\":\"" ).append(String.valueOf(getInput5()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input6\":\"" ).append(String.valueOf(getInput6()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"output\":\"" ).append(String.valueOf(getOutput()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"voltage\":\"" ).append(String.valueOf(getVoltage()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"cellLevel\":\"" ).append(String.valueOf(getCellLevel()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"latitude\":\"" ).append(String.valueOf(getLatitude()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"longitude\":\"" ).append(String.valueOf(getLongitude()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"status\":\"" ).append(String.valueOf(getStatus()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deleted\":\"" ).append(String.valueOf(getDeleted()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"voltageSlave\":\"" ).append(String.valueOf(getVoltageSlave()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"type\":\"" ).append(String.valueOf(getType()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"pnType\":\"" ).append(String.valueOf(getPnType()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastDetectedSpeed\":\"" ).append(String.valueOf(getDeviceLastDetectedSpeed()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastNumberOfEixos\":\"" ).append(String.valueOf(getDeviceLastNumberOfEixos()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastDetectedWeight\":\"" ).append(String.valueOf(getDeviceLastDetectedWeight()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastDetectionStartDate\":\"" ).append(String.valueOf(getLastDetectionStartDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastDetectionEndDate\":\"" ).append(String.valueOf(getLastDetectionEndDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastDetectedTemperature\":\"" ).append(String.valueOf(getDeviceLastDetectedTemperature()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor2\":\"" ).append(String.valueOf(getSensor2()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor3\":\"" ).append(String.valueOf(getSensor3()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor4\":\"" ).append(String.valueOf(getSensor4()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor5\":\"" ).append(String.valueOf(getSensor5()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor6\":\"" ).append(String.valueOf(getSensor6()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor7\":\"" ).append(String.valueOf(getSensor7()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor8\":\"" ).append(String.valueOf(getSensor8()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor1\":\"" ).append(String.valueOf(getSensor1()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"statusDescription\":\"" ).append(String.valueOf(getStatusDescription()) ).append("\"");
		sResult.append("}");
		return sResult.toString();
	}

	/** toList method*/
	public java.util.List<String> toList()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( String.valueOf(getId()));
		list.add( String.valueOf(getExternalId()));
		list.add( String.valueOf(getName()));
		list.add( String.valueOf(getExternalName()));
		list.add( String.valueOf(getUpId()));
		list.add( String.valueOf(getKm()));
		list.add( String.valueOf(getLocal()));
		list.add( String.valueOf(getLastDataDate()));
		list.add( String.valueOf(getLastActivationDate()));
		list.add( String.valueOf(getCreationDate()));
		list.add( String.valueOf(getUpdateDate()));
		list.add( String.valueOf(getInput1()));
		list.add( String.valueOf(getInput2()));
		list.add( String.valueOf(getInput3()));
		list.add( String.valueOf(getInput4()));
		list.add( String.valueOf(getInput5()));
		list.add( String.valueOf(getInput6()));
		list.add( String.valueOf(getOutput()));
		list.add( String.valueOf(getVoltage()));
		list.add( String.valueOf(getCellLevel()));
		list.add( String.valueOf(getLatitude()));
		list.add( String.valueOf(getLongitude()));
		list.add( String.valueOf(getStatus()));
		list.add( String.valueOf(getDeleted()));
		list.add( String.valueOf(getVoltageSlave()));
		list.add( String.valueOf(getType()));
		list.add( String.valueOf(getPnType()));
		list.add( String.valueOf(getDeviceLastDetectedSpeed()));
		list.add( String.valueOf(getDeviceLastNumberOfEixos()));
		list.add( String.valueOf(getDeviceLastDetectedWeight()));
		list.add( String.valueOf(getLastDetectionStartDate()));
		list.add( String.valueOf(getLastDetectionEndDate()));
		list.add( String.valueOf(getDeviceLastDetectedTemperature()));
		list.add( String.valueOf(getSensor2()));
		list.add( String.valueOf(getSensor3()));
		list.add( String.valueOf(getSensor4()));
		list.add( String.valueOf(getSensor5()));
		list.add( String.valueOf(getSensor6()));
		list.add( String.valueOf(getSensor7()));
		list.add( String.valueOf(getSensor8()));
		list.add( String.valueOf(getSensor1()));
		list.add( String.valueOf(getStatusDescription()));
		return list;
	}

	/** getAttributeNames method*/
	public java.util.List<String> getAttributeNames()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( "id");
		list.add( "externalId");
		list.add( "name");
		list.add( "externalName");
		list.add( "upId");
		list.add( "km");
		list.add( "local");
		list.add( "lastDataDate");
		list.add( "lastActivationDate");
		list.add( "creationDate");
		list.add( "updateDate");
		list.add( "input1");
		list.add( "input2");
		list.add( "input3");
		list.add( "input4");
		list.add( "input5");
		list.add( "input6");
		list.add( "output");
		list.add( "voltage");
		list.add( "cellLevel");
		list.add( "latitude");
		list.add( "longitude");
		list.add( "status");
		list.add( "deleted");
		list.add( "voltageSlave");
		list.add( "type");
		list.add( "pnType");
		list.add( "deviceLastDetectedSpeed");
		list.add( "deviceLastNumberOfEixos");
		list.add( "deviceLastDetectedWeight");
		list.add( "lastDetectionStartDate");
		list.add( "lastDetectionEndDate");
		list.add( "deviceLastDetectedTemperature");
		list.add( "sensor2");
		list.add( "sensor3");
		list.add( "sensor4");
		list.add( "sensor5");
		list.add( "sensor6");
		list.add( "sensor7");
		list.add( "sensor8");
		list.add( "sensor1");
		list.add( "statusDescription");
		return list;
	}

}
	//** Database fields
