// class generated by JConcept Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model;

// import JConcept Database library
// For BigDecimal attribute
import java.math.BigDecimal;
// For Date attribute
import java.util.Date;

import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.DbObjectMapping;
import org.neodatis.rdb.PrimaryKey;
import org.neodatis.rdb.Service;
import org.neodatis.rdb.implementation.DefaultPrimaryKey;
import org.neodatis.rdb.query.DefaultDBTable;

public class PnData extends org.neodatis.rdb.DbObjectWithLongId  implements DbObjectMapping , org.neodatis.rdb.ToX
 ,java.io.Serializable
{
	//** Database fields
	protected Long dbid;
	protected String dbname;
	protected String dbup_name;
	protected String dbkm;
	protected Date dbdate;
	protected Long dbinput1;
	protected Long dbinput2;
	protected Long dbinput3;
	protected Long dbinput4;
	protected Long dbinput5;
	protected Long dbinput6;
	protected Long dboutput1;
	protected BigDecimal dbvoltage;
	protected BigDecimal dbcell_level;
	protected Long dbup_id;
	protected Long dbpn_id;
	protected Long dbtype;
	protected BigDecimal dbvoltage_slave;
	protected Long dbpn_type;
	protected Date dblast_detection_start_date;
	protected Date dblast_detection_end_date;
	protected Long dbsensor7;
	protected Long dbsensor8;
	protected Long dbsensor2;
	protected Long dbsensor3;
	protected Long dbsensor4;
	protected Long dbsensor5;
	protected Long dbsensor6;
	protected BigDecimal dbdevice_last_detected_speed;
	protected Long dbdevice_last_number_of_eixos;
	protected BigDecimal dbdevice_last_detected_weight;
	protected Long dbdevice_last_detected_temperature;
	protected Long dbsensor1;
	//** Db Object
	public static Service<PnData> DB = new Service<PnData>(PnData.class);

	//** Construtor
	public PnData()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("id");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("pn_data");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbid = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbid;
	}

	// Setter for attribute name
	public void setName( String in_name ) 
	{
		dbname = in_name;
	}

	// Getter for attribute name
	public String getName()
	{
		return dbname;
	}

	// Setter for attribute upName
	public void setUpName( String in_upName ) 
	{
		dbup_name = in_upName;
	}

	// Getter for attribute upName
	public String getUpName()
	{
		return dbup_name;
	}

	// Setter for attribute km
	public void setKm( String in_km ) 
	{
		dbkm = in_km;
	}

	// Getter for attribute km
	public String getKm()
	{
		return dbkm;
	}

	// Setter for attribute date
	public void setDate( Date in_date ) 
	{
		dbdate = in_date;
	}

	// Getter for attribute date
	public Date getDate()
	{
		return dbdate;
	}

	// Setter for attribute input1
	public void setInput1( Long in_input1 ) 
	{
		dbinput1 = in_input1;
	}

	// Getter for attribute input1
	public Long getInput1()
	{
		return dbinput1;
	}

	// Setter for attribute input2
	public void setInput2( Long in_input2 ) 
	{
		dbinput2 = in_input2;
	}

	// Getter for attribute input2
	public Long getInput2()
	{
		return dbinput2;
	}

	// Setter for attribute input3
	public void setInput3( Long in_input3 ) 
	{
		dbinput3 = in_input3;
	}

	// Getter for attribute input3
	public Long getInput3()
	{
		return dbinput3;
	}

	// Setter for attribute input4
	public void setInput4( Long in_input4 ) 
	{
		dbinput4 = in_input4;
	}

	// Getter for attribute input4
	public Long getInput4()
	{
		return dbinput4;
	}

	// Setter for attribute input5
	public void setInput5( Long in_input5 ) 
	{
		dbinput5 = in_input5;
	}

	// Getter for attribute input5
	public Long getInput5()
	{
		return dbinput5;
	}

	// Setter for attribute input6
	public void setInput6( Long in_input6 ) 
	{
		dbinput6 = in_input6;
	}

	// Getter for attribute input6
	public Long getInput6()
	{
		return dbinput6;
	}

	// Setter for attribute output1
	public void setOutput1( Long in_output1 ) 
	{
		dboutput1 = in_output1;
	}

	// Getter for attribute output1
	public Long getOutput1()
	{
		return dboutput1;
	}

	// Setter for attribute voltage
	public void setVoltage( BigDecimal in_voltage ) 
	{
		dbvoltage = in_voltage;
	}

	// Getter for attribute voltage
	public BigDecimal getVoltage()
	{
		return dbvoltage;
	}

	// Setter for attribute cellLevel
	public void setCellLevel( BigDecimal in_cellLevel ) 
	{
		dbcell_level = in_cellLevel;
	}

	// Getter for attribute cellLevel
	public BigDecimal getCellLevel()
	{
		return dbcell_level;
	}

	// Setter for attribute upId
	public void setUpId( Long in_upId ) 
	{
		dbup_id = in_upId;
	}

	// Getter for attribute upId
	public Long getUpId()
	{
		return dbup_id;
	}

	// Setter for attribute pnId
	public void setPnId( Long in_pnId ) 
	{
		dbpn_id = in_pnId;
	}

	// Getter for attribute pnId
	public Long getPnId()
	{
		return dbpn_id;
	}

	// Setter for attribute type
	public void setType( Long in_type ) 
	{
		dbtype = in_type;
	}

	// Getter for attribute type
	public Long getType()
	{
		return dbtype;
	}

	// Setter for attribute voltageSlave
	public void setVoltageSlave( BigDecimal in_voltageSlave ) 
	{
		dbvoltage_slave = in_voltageSlave;
	}

	// Getter for attribute voltageSlave
	public BigDecimal getVoltageSlave()
	{
		return dbvoltage_slave;
	}

	// Setter for attribute pnType
	public void setPnType( Long in_pnType ) 
	{
		dbpn_type = in_pnType;
	}

	// Getter for attribute pnType
	public Long getPnType()
	{
		return dbpn_type;
	}

	// Setter for attribute lastDetectionStartDate
	public void setLastDetectionStartDate( Date in_lastDetectionStartDate ) 
	{
		dblast_detection_start_date = in_lastDetectionStartDate;
	}

	// Getter for attribute lastDetectionStartDate
	public Date getLastDetectionStartDate()
	{
		return dblast_detection_start_date;
	}

	// Setter for attribute lastDetectionEndDate
	public void setLastDetectionEndDate( Date in_lastDetectionEndDate ) 
	{
		dblast_detection_end_date = in_lastDetectionEndDate;
	}

	// Getter for attribute lastDetectionEndDate
	public Date getLastDetectionEndDate()
	{
		return dblast_detection_end_date;
	}

	// Setter for attribute sensor7
	public void setSensor7( Long in_sensor7 ) 
	{
		dbsensor7 = in_sensor7;
	}

	// Getter for attribute sensor7
	public Long getSensor7()
	{
		return dbsensor7;
	}

	// Setter for attribute sensor8
	public void setSensor8( Long in_sensor8 ) 
	{
		dbsensor8 = in_sensor8;
	}

	// Getter for attribute sensor8
	public Long getSensor8()
	{
		return dbsensor8;
	}

	// Setter for attribute sensor2
	public void setSensor2( Long in_sensor2 ) 
	{
		dbsensor2 = in_sensor2;
	}

	// Getter for attribute sensor2
	public Long getSensor2()
	{
		return dbsensor2;
	}

	// Setter for attribute sensor3
	public void setSensor3( Long in_sensor3 ) 
	{
		dbsensor3 = in_sensor3;
	}

	// Getter for attribute sensor3
	public Long getSensor3()
	{
		return dbsensor3;
	}

	// Setter for attribute sensor4
	public void setSensor4( Long in_sensor4 ) 
	{
		dbsensor4 = in_sensor4;
	}

	// Getter for attribute sensor4
	public Long getSensor4()
	{
		return dbsensor4;
	}

	// Setter for attribute sensor5
	public void setSensor5( Long in_sensor5 ) 
	{
		dbsensor5 = in_sensor5;
	}

	// Getter for attribute sensor5
	public Long getSensor5()
	{
		return dbsensor5;
	}

	// Setter for attribute sensor6
	public void setSensor6( Long in_sensor6 ) 
	{
		dbsensor6 = in_sensor6;
	}

	// Getter for attribute sensor6
	public Long getSensor6()
	{
		return dbsensor6;
	}

	// Setter for attribute deviceLastDetectedSpeed
	public void setDeviceLastDetectedSpeed( BigDecimal in_deviceLastDetectedSpeed ) 
	{
		dbdevice_last_detected_speed = in_deviceLastDetectedSpeed;
	}

	// Getter for attribute deviceLastDetectedSpeed
	public BigDecimal getDeviceLastDetectedSpeed()
	{
		return dbdevice_last_detected_speed;
	}

	// Setter for attribute deviceLastNumberOfEixos
	public void setDeviceLastNumberOfEixos( Long in_deviceLastNumberOfEixos ) 
	{
		dbdevice_last_number_of_eixos = in_deviceLastNumberOfEixos;
	}

	// Getter for attribute deviceLastNumberOfEixos
	public Long getDeviceLastNumberOfEixos()
	{
		return dbdevice_last_number_of_eixos;
	}

	// Setter for attribute deviceLastDetectedWeight
	public void setDeviceLastDetectedWeight( BigDecimal in_deviceLastDetectedWeight ) 
	{
		dbdevice_last_detected_weight = in_deviceLastDetectedWeight;
	}

	// Getter for attribute deviceLastDetectedWeight
	public BigDecimal getDeviceLastDetectedWeight()
	{
		return dbdevice_last_detected_weight;
	}

	// Setter for attribute deviceLastDetectedTemperature
	public void setDeviceLastDetectedTemperature( Long in_deviceLastDetectedTemperature ) 
	{
		dbdevice_last_detected_temperature = in_deviceLastDetectedTemperature;
	}

	// Getter for attribute deviceLastDetectedTemperature
	public Long getDeviceLastDetectedTemperature()
	{
		return dbdevice_last_detected_temperature;
	}

	// Setter for attribute sensor1
	public void setSensor1( Long in_sensor1 ) 
	{
		dbsensor1 = in_sensor1;
	}

	// Getter for attribute sensor1
	public Long getSensor1()
	{
		return dbsensor1;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t name : " ).append( getName()).append("\n");
		sResult.append( "\t upName : " ).append( getUpName()).append("\n");
		sResult.append( "\t km : " ).append( getKm()).append("\n");
		sResult.append( "\t date : " ).append( getDate()).append("\n");
		sResult.append( "\t input1 : " ).append( getInput1()).append("\n");
		sResult.append( "\t input2 : " ).append( getInput2()).append("\n");
		sResult.append( "\t input3 : " ).append( getInput3()).append("\n");
		sResult.append( "\t input4 : " ).append( getInput4()).append("\n");
		sResult.append( "\t input5 : " ).append( getInput5()).append("\n");
		sResult.append( "\t input6 : " ).append( getInput6()).append("\n");
		sResult.append( "\t output1 : " ).append( getOutput1()).append("\n");
		sResult.append( "\t voltage : " ).append( getVoltage()).append("\n");
		sResult.append( "\t cellLevel : " ).append( getCellLevel()).append("\n");
		sResult.append( "\t upId : " ).append( getUpId()).append("\n");
		sResult.append( "\t pnId : " ).append( getPnId()).append("\n");
		sResult.append( "\t type : " ).append( getType()).append("\n");
		sResult.append( "\t voltageSlave : " ).append( getVoltageSlave()).append("\n");
		sResult.append( "\t pnType : " ).append( getPnType()).append("\n");
		sResult.append( "\t lastDetectionStartDate : " ).append( getLastDetectionStartDate()).append("\n");
		sResult.append( "\t lastDetectionEndDate : " ).append( getLastDetectionEndDate()).append("\n");
		sResult.append( "\t sensor7 : " ).append( getSensor7()).append("\n");
		sResult.append( "\t sensor8 : " ).append( getSensor8()).append("\n");
		sResult.append( "\t sensor2 : " ).append( getSensor2()).append("\n");
		sResult.append( "\t sensor3 : " ).append( getSensor3()).append("\n");
		sResult.append( "\t sensor4 : " ).append( getSensor4()).append("\n");
		sResult.append( "\t sensor5 : " ).append( getSensor5()).append("\n");
		sResult.append( "\t sensor6 : " ).append( getSensor6()).append("\n");
		sResult.append( "\t deviceLastDetectedSpeed : " ).append( getDeviceLastDetectedSpeed()).append("\n");
		sResult.append( "\t deviceLastNumberOfEixos : " ).append( getDeviceLastNumberOfEixos()).append("\n");
		sResult.append( "\t deviceLastDetectedWeight : " ).append( getDeviceLastDetectedWeight()).append("\n");
		sResult.append( "\t deviceLastDetectedTemperature : " ).append( getDeviceLastDetectedTemperature()).append("\n");
		sResult.append( "\t sensor1 : " ).append( getSensor1()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

	/** toMap method*/
	public java.util.Map<String,Object> toMap()
	{

		java.util.Map<String,Object> map = new java.util.HashMap<String,Object>();
		map.put( "id" , String.valueOf(getId()));
		map.put( "name" , String.valueOf(getName()));
		map.put( "upName" , String.valueOf(getUpName()));
		map.put( "km" , String.valueOf(getKm()));
		map.put( "date" , String.valueOf(getDate()));
		map.put( "input1" , String.valueOf(getInput1()));
		map.put( "input2" , String.valueOf(getInput2()));
		map.put( "input3" , String.valueOf(getInput3()));
		map.put( "input4" , String.valueOf(getInput4()));
		map.put( "input5" , String.valueOf(getInput5()));
		map.put( "input6" , String.valueOf(getInput6()));
		map.put( "output1" , String.valueOf(getOutput1()));
		map.put( "voltage" , String.valueOf(getVoltage()));
		map.put( "cellLevel" , String.valueOf(getCellLevel()));
		map.put( "upId" , String.valueOf(getUpId()));
		map.put( "pnId" , String.valueOf(getPnId()));
		map.put( "type" , String.valueOf(getType()));
		map.put( "voltageSlave" , String.valueOf(getVoltageSlave()));
		map.put( "pnType" , String.valueOf(getPnType()));
		map.put( "lastDetectionStartDate" , String.valueOf(getLastDetectionStartDate()));
		map.put( "lastDetectionEndDate" , String.valueOf(getLastDetectionEndDate()));
		map.put( "sensor7" , String.valueOf(getSensor7()));
		map.put( "sensor8" , String.valueOf(getSensor8()));
		map.put( "sensor2" , String.valueOf(getSensor2()));
		map.put( "sensor3" , String.valueOf(getSensor3()));
		map.put( "sensor4" , String.valueOf(getSensor4()));
		map.put( "sensor5" , String.valueOf(getSensor5()));
		map.put( "sensor6" , String.valueOf(getSensor6()));
		map.put( "deviceLastDetectedSpeed" , String.valueOf(getDeviceLastDetectedSpeed()));
		map.put( "deviceLastNumberOfEixos" , String.valueOf(getDeviceLastNumberOfEixos()));
		map.put( "deviceLastDetectedWeight" , String.valueOf(getDeviceLastDetectedWeight()));
		map.put( "deviceLastDetectedTemperature" , String.valueOf(getDeviceLastDetectedTemperature()));
		map.put( "sensor1" , String.valueOf(getSensor1()));
		return map;
	}

	/** toJSon method*/
	public String toJSon()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("{");
		sResult.append( "\"id\":\"" ).append(String.valueOf(getId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"name\":\"" ).append(String.valueOf(getName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"upName\":\"" ).append(String.valueOf(getUpName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"km\":\"" ).append(String.valueOf(getKm()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"date\":\"" ).append(String.valueOf(getDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input1\":\"" ).append(String.valueOf(getInput1()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input2\":\"" ).append(String.valueOf(getInput2()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input3\":\"" ).append(String.valueOf(getInput3()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input4\":\"" ).append(String.valueOf(getInput4()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input5\":\"" ).append(String.valueOf(getInput5()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"input6\":\"" ).append(String.valueOf(getInput6()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"output1\":\"" ).append(String.valueOf(getOutput1()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"voltage\":\"" ).append(String.valueOf(getVoltage()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"cellLevel\":\"" ).append(String.valueOf(getCellLevel()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"upId\":\"" ).append(String.valueOf(getUpId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"pnId\":\"" ).append(String.valueOf(getPnId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"type\":\"" ).append(String.valueOf(getType()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"voltageSlave\":\"" ).append(String.valueOf(getVoltageSlave()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"pnType\":\"" ).append(String.valueOf(getPnType()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastDetectionStartDate\":\"" ).append(String.valueOf(getLastDetectionStartDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastDetectionEndDate\":\"" ).append(String.valueOf(getLastDetectionEndDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor7\":\"" ).append(String.valueOf(getSensor7()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor8\":\"" ).append(String.valueOf(getSensor8()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor2\":\"" ).append(String.valueOf(getSensor2()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor3\":\"" ).append(String.valueOf(getSensor3()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor4\":\"" ).append(String.valueOf(getSensor4()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor5\":\"" ).append(String.valueOf(getSensor5()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor6\":\"" ).append(String.valueOf(getSensor6()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastDetectedSpeed\":\"" ).append(String.valueOf(getDeviceLastDetectedSpeed()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastNumberOfEixos\":\"" ).append(String.valueOf(getDeviceLastNumberOfEixos()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastDetectedWeight\":\"" ).append(String.valueOf(getDeviceLastDetectedWeight()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"deviceLastDetectedTemperature\":\"" ).append(String.valueOf(getDeviceLastDetectedTemperature()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"sensor1\":\"" ).append(String.valueOf(getSensor1()) ).append("\"");
		sResult.append("}");
		return sResult.toString();
	}

	/** toList method*/
	public java.util.List<String> toList()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( String.valueOf(getId()));
		list.add( String.valueOf(getName()));
		list.add( String.valueOf(getUpName()));
		list.add( String.valueOf(getKm()));
		list.add( String.valueOf(getDate()));
		list.add( String.valueOf(getInput1()));
		list.add( String.valueOf(getInput2()));
		list.add( String.valueOf(getInput3()));
		list.add( String.valueOf(getInput4()));
		list.add( String.valueOf(getInput5()));
		list.add( String.valueOf(getInput6()));
		list.add( String.valueOf(getOutput1()));
		list.add( String.valueOf(getVoltage()));
		list.add( String.valueOf(getCellLevel()));
		list.add( String.valueOf(getUpId()));
		list.add( String.valueOf(getPnId()));
		list.add( String.valueOf(getType()));
		list.add( String.valueOf(getVoltageSlave()));
		list.add( String.valueOf(getPnType()));
		list.add( String.valueOf(getLastDetectionStartDate()));
		list.add( String.valueOf(getLastDetectionEndDate()));
		list.add( String.valueOf(getSensor7()));
		list.add( String.valueOf(getSensor8()));
		list.add( String.valueOf(getSensor2()));
		list.add( String.valueOf(getSensor3()));
		list.add( String.valueOf(getSensor4()));
		list.add( String.valueOf(getSensor5()));
		list.add( String.valueOf(getSensor6()));
		list.add( String.valueOf(getDeviceLastDetectedSpeed()));
		list.add( String.valueOf(getDeviceLastNumberOfEixos()));
		list.add( String.valueOf(getDeviceLastDetectedWeight()));
		list.add( String.valueOf(getDeviceLastDetectedTemperature()));
		list.add( String.valueOf(getSensor1()));
		return list;
	}

	/** getAttributeNames method*/
	public java.util.List<String> getAttributeNames()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( "id");
		list.add( "name");
		list.add( "upName");
		list.add( "km");
		list.add( "date");
		list.add( "input1");
		list.add( "input2");
		list.add( "input3");
		list.add( "input4");
		list.add( "input5");
		list.add( "input6");
		list.add( "output1");
		list.add( "voltage");
		list.add( "cellLevel");
		list.add( "upId");
		list.add( "pnId");
		list.add( "type");
		list.add( "voltageSlave");
		list.add( "pnType");
		list.add( "lastDetectionStartDate");
		list.add( "lastDetectionEndDate");
		list.add( "sensor7");
		list.add( "sensor8");
		list.add( "sensor2");
		list.add( "sensor3");
		list.add( "sensor4");
		list.add( "sensor5");
		list.add( "sensor6");
		list.add( "deviceLastDetectedSpeed");
		list.add( "deviceLastNumberOfEixos");
		list.add( "deviceLastDetectedWeight");
		list.add( "deviceLastDetectedTemperature");
		list.add( "sensor1");
		return list;
	}

}
	//** Database fields
