// class generated by JConcept Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model;

// import JConcept Database library
// For BigDecimal attribute
import java.math.BigDecimal;
// For Date attribute
import java.util.Date;

import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.DbObjectMapping;
import org.neodatis.rdb.PrimaryKey;
import org.neodatis.rdb.Service;
import org.neodatis.rdb.implementation.DefaultPrimaryKey;
import org.neodatis.rdb.query.DefaultDBTable;

public class TrainTracking extends org.neodatis.rdb.DbObjectWithLongId  implements DbObjectMapping , org.neodatis.rdb.ToX
 ,java.io.Serializable
{
	//** Database fields
	protected Long dbid;
	protected String dbpn_name;
	protected Date dbdata_date;
	protected Date dbenter_date;
	protected Date dbexit_date;
	protected Long dbtrain_id;
	protected String dbtrain_prefix;
	protected String dbkm;
	protected BigDecimal dbstartkm;
	protected BigDecimal dbendkm;
	protected String dblocal;
	protected Date dbmanagment_date;
	protected Long dbdata_status;
	protected Long dbactivation_status;
	protected Long dbpn_data_id;
	protected Long dbweb_service_call_id;
	protected String dbdescription;
	//** Db Object
	public static Service<TrainTracking> DB = new Service<TrainTracking>(TrainTracking.class);

	//** Construtor
	public TrainTracking()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("id");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("train_tracking");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbid = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbid;
	}

	// Setter for attribute pnName
	public void setPnName( String in_pnName ) 
	{
		dbpn_name = in_pnName;
	}

	// Getter for attribute pnName
	public String getPnName()
	{
		return dbpn_name;
	}

	// Setter for attribute dataDate
	public void setDataDate( Date in_dataDate ) 
	{
		dbdata_date = in_dataDate;
	}

	// Getter for attribute dataDate
	public Date getDataDate()
	{
		return dbdata_date;
	}

	// Setter for attribute enterDate
	public void setEnterDate( Date in_enterDate ) 
	{
		dbenter_date = in_enterDate;
	}

	// Getter for attribute enterDate
	public Date getEnterDate()
	{
		return dbenter_date;
	}

	// Setter for attribute exitDate
	public void setExitDate( Date in_exitDate ) 
	{
		dbexit_date = in_exitDate;
	}

	// Getter for attribute exitDate
	public Date getExitDate()
	{
		return dbexit_date;
	}

	// Setter for attribute trainId
	public void setTrainId( Long in_trainId ) 
	{
		dbtrain_id = in_trainId;
	}

	// Getter for attribute trainId
	public Long getTrainId()
	{
		return dbtrain_id;
	}

	// Setter for attribute trainPrefix
	public void setTrainPrefix( String in_trainPrefix ) 
	{
		dbtrain_prefix = in_trainPrefix;
	}

	// Getter for attribute trainPrefix
	public String getTrainPrefix()
	{
		return dbtrain_prefix;
	}

	// Setter for attribute km
	public void setKm( String in_km ) 
	{
		dbkm = in_km;
	}

	// Getter for attribute km
	public String getKm()
	{
		return dbkm;
	}

	// Setter for attribute startkm
	public void setStartkm( BigDecimal in_startkm ) 
	{
		dbstartkm = in_startkm;
	}

	// Getter for attribute startkm
	public BigDecimal getStartkm()
	{
		return dbstartkm;
	}

	// Setter for attribute endkm
	public void setEndkm( BigDecimal in_endkm ) 
	{
		dbendkm = in_endkm;
	}

	// Getter for attribute endkm
	public BigDecimal getEndkm()
	{
		return dbendkm;
	}

	// Setter for attribute local
	public void setLocal( String in_local ) 
	{
		dblocal = in_local;
	}

	// Getter for attribute local
	public String getLocal()
	{
		return dblocal;
	}

	// Setter for attribute managmentDate
	public void setManagmentDate( Date in_managmentDate ) 
	{
		dbmanagment_date = in_managmentDate;
	}

	// Getter for attribute managmentDate
	public Date getManagmentDate()
	{
		return dbmanagment_date;
	}

	// Setter for attribute dataStatus
	public void setDataStatus( Long in_dataStatus ) 
	{
		dbdata_status = in_dataStatus;
	}

	// Getter for attribute dataStatus
	public Long getDataStatus()
	{
		return dbdata_status;
	}

	// Setter for attribute activationStatus
	public void setActivationStatus( Long in_activationStatus ) 
	{
		dbactivation_status = in_activationStatus;
	}

	// Getter for attribute activationStatus
	public Long getActivationStatus()
	{
		return dbactivation_status;
	}

	// Setter for attribute pnDataId
	public void setPnDataId( Long in_pnDataId ) 
	{
		dbpn_data_id = in_pnDataId;
	}

	// Getter for attribute pnDataId
	public Long getPnDataId()
	{
		return dbpn_data_id;
	}

	// Setter for attribute webServiceCallId
	public void setWebServiceCallId( Long in_webServiceCallId ) 
	{
		dbweb_service_call_id = in_webServiceCallId;
	}

	// Getter for attribute webServiceCallId
	public Long getWebServiceCallId()
	{
		return dbweb_service_call_id;
	}

	// Setter for attribute description
	public void setDescription( String in_description ) 
	{
		dbdescription = in_description;
	}

	// Getter for attribute description
	public String getDescription()
	{
		return dbdescription;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t pnName : " ).append( getPnName()).append("\n");
		sResult.append( "\t dataDate : " ).append( getDataDate()).append("\n");
		sResult.append( "\t enterDate : " ).append( getEnterDate()).append("\n");
		sResult.append( "\t exitDate : " ).append( getExitDate()).append("\n");
		sResult.append( "\t trainId : " ).append( getTrainId()).append("\n");
		sResult.append( "\t trainPrefix : " ).append( getTrainPrefix()).append("\n");
		sResult.append( "\t km : " ).append( getKm()).append("\n");
		sResult.append( "\t startkm : " ).append( getStartkm()).append("\n");
		sResult.append( "\t endkm : " ).append( getEndkm()).append("\n");
		sResult.append( "\t local : " ).append( getLocal()).append("\n");
		sResult.append( "\t managmentDate : " ).append( getManagmentDate()).append("\n");
		sResult.append( "\t dataStatus : " ).append( getDataStatus()).append("\n");
		sResult.append( "\t activationStatus : " ).append( getActivationStatus()).append("\n");
		sResult.append( "\t pnDataId : " ).append( getPnDataId()).append("\n");
		sResult.append( "\t webServiceCallId : " ).append( getWebServiceCallId()).append("\n");
		sResult.append( "\t description : " ).append( getDescription()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

	/** toMap method*/
	public java.util.Map<String,Object> toMap()
	{

		java.util.Map<String,Object> map = new java.util.HashMap<String,Object>();
		map.put( "id" , String.valueOf(getId()));
		map.put( "pnName" , String.valueOf(getPnName()));
		map.put( "dataDate" , String.valueOf(getDataDate()));
		map.put( "enterDate" , String.valueOf(getEnterDate()));
		map.put( "exitDate" , String.valueOf(getExitDate()));
		map.put( "trainId" , String.valueOf(getTrainId()));
		map.put( "trainPrefix" , String.valueOf(getTrainPrefix()));
		map.put( "km" , String.valueOf(getKm()));
		map.put( "startkm" , String.valueOf(getStartkm()));
		map.put( "endkm" , String.valueOf(getEndkm()));
		map.put( "local" , String.valueOf(getLocal()));
		map.put( "managmentDate" , String.valueOf(getManagmentDate()));
		map.put( "dataStatus" , String.valueOf(getDataStatus()));
		map.put( "activationStatus" , String.valueOf(getActivationStatus()));
		map.put( "pnDataId" , String.valueOf(getPnDataId()));
		map.put( "webServiceCallId" , String.valueOf(getWebServiceCallId()));
		map.put( "description" , String.valueOf(getDescription()));
		return map;
	}

	/** toJSon method*/
	public String toJSon()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("{");
		sResult.append( "\"id\":\"" ).append(String.valueOf(getId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"pnName\":\"" ).append(String.valueOf(getPnName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"dataDate\":\"" ).append(String.valueOf(getDataDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"enterDate\":\"" ).append(String.valueOf(getEnterDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"exitDate\":\"" ).append(String.valueOf(getExitDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"trainId\":\"" ).append(String.valueOf(getTrainId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"trainPrefix\":\"" ).append(String.valueOf(getTrainPrefix()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"km\":\"" ).append(String.valueOf(getKm()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"startkm\":\"" ).append(String.valueOf(getStartkm()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"endkm\":\"" ).append(String.valueOf(getEndkm()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"local\":\"" ).append(String.valueOf(getLocal()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"managmentDate\":\"" ).append(String.valueOf(getManagmentDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"dataStatus\":\"" ).append(String.valueOf(getDataStatus()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"activationStatus\":\"" ).append(String.valueOf(getActivationStatus()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"pnDataId\":\"" ).append(String.valueOf(getPnDataId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"webServiceCallId\":\"" ).append(String.valueOf(getWebServiceCallId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"description\":\"" ).append(String.valueOf(getDescription()) ).append("\"");
		sResult.append("}");
		return sResult.toString();
	}

	/** toList method*/
	public java.util.List<String> toList()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( String.valueOf(getId()));
		list.add( String.valueOf(getPnName()));
		list.add( String.valueOf(getDataDate()));
		list.add( String.valueOf(getEnterDate()));
		list.add( String.valueOf(getExitDate()));
		list.add( String.valueOf(getTrainId()));
		list.add( String.valueOf(getTrainPrefix()));
		list.add( String.valueOf(getKm()));
		list.add( String.valueOf(getStartkm()));
		list.add( String.valueOf(getEndkm()));
		list.add( String.valueOf(getLocal()));
		list.add( String.valueOf(getManagmentDate()));
		list.add( String.valueOf(getDataStatus()));
		list.add( String.valueOf(getActivationStatus()));
		list.add( String.valueOf(getPnDataId()));
		list.add( String.valueOf(getWebServiceCallId()));
		list.add( String.valueOf(getDescription()));
		return list;
	}

	/** getAttributeNames method*/
	public java.util.List<String> getAttributeNames()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( "id");
		list.add( "pnName");
		list.add( "dataDate");
		list.add( "enterDate");
		list.add( "exitDate");
		list.add( "trainId");
		list.add( "trainPrefix");
		list.add( "km");
		list.add( "startkm");
		list.add( "endkm");
		list.add( "local");
		list.add( "managmentDate");
		list.add( "dataStatus");
		list.add( "activationStatus");
		list.add( "pnDataId");
		list.add( "webServiceCallId");
		list.add( "description");
		return list;
	}

}
	//** Database fields
