// class generated by JConcept Database ClassBuilder 2.0
package org.neodatis.rdb.mentor.model;

// import JConcept Database library
// For Date attribute
import java.util.Date;

import org.neodatis.rdb.DBTable;
import org.neodatis.rdb.DbObjectMapping;
import org.neodatis.rdb.PrimaryKey;
import org.neodatis.rdb.Service;
import org.neodatis.rdb.implementation.DefaultPrimaryKey;
import org.neodatis.rdb.query.DefaultDBTable;
// For BigDecimal attribute

public class Users extends org.neodatis.rdb.DbObjectWithLongId  implements DbObjectMapping , org.neodatis.rdb.ToX
 ,java.io.Serializable
{
	//** Database fields
	protected Long dbid;
	protected String dbname;
	protected String dblogin;
	protected String dbpassword;
	protected Date dbcreation_date;
	protected Date dblast_login_date;
	protected Long dbstatus;
	protected Long dbprofile_id;
	//** Db Object
	public static Service<Users> DB = new Service<Users>(Users.class);

	//** Construtor
	public Users()
	{
	}

	//** To get the primary key field name
	public PrimaryKey getPrimaryKey()
	{
		return new DefaultPrimaryKey("id");
	}

	//** To get the table name
	public DBTable getTable()
	{
		return new DefaultDBTable("users");
	}

	//** To check equality
	public boolean equals(Object in_object)
	{
		DbObjectMapping objectToCompare = (DbObjectMapping) in_object;
		try 
		{
			return getPrimaryKey().getValue(this).equals(objectToCompare.getPrimaryKey().getValue(objectToCompare));
		} 
		catch(Exception e)
		{
			return false; 
		}
	}

	//** Setters and Getters

	// Setter for attribute id
	public void setId( Long in_id ) 
	{
		dbid = in_id;
	}

	// Getter for attribute id
	public Long getId()
	{
		return dbid;
	}

	// Setter for attribute name
	public void setName( String in_name ) 
	{
		dbname = in_name;
	}

	// Getter for attribute name
	public String getName()
	{
		return dbname;
	}

	// Setter for attribute login
	public void setLogin( String in_login ) 
	{
		dblogin = in_login;
	}

	// Getter for attribute login
	public String getLogin()
	{
		return dblogin;
	}

	// Setter for attribute password
	public void setPassword( String in_password ) 
	{
		dbpassword = in_password;
	}

	// Getter for attribute password
	public String getPassword()
	{
		return dbpassword;
	}

	// Setter for attribute creationDate
	public void setCreationDate( Date in_creationDate ) 
	{
		dbcreation_date = in_creationDate;
	}

	// Getter for attribute creationDate
	public Date getCreationDate()
	{
		return dbcreation_date;
	}

	// Setter for attribute lastLoginDate
	public void setLastLoginDate( Date in_lastLoginDate ) 
	{
		dblast_login_date = in_lastLoginDate;
	}

	// Getter for attribute lastLoginDate
	public Date getLastLoginDate()
	{
		return dblast_login_date;
	}

	// Setter for attribute status
	public void setStatus( Long in_status ) 
	{
		dbstatus = in_status;
	}

	// Getter for attribute status
	public Long getStatus()
	{
		return dbstatus;
	}

	// Setter for attribute profileId
	public void setProfileId( Long in_profileId ) 
	{
		dbprofile_id = in_profileId;
	}

	// Getter for attribute profileId
	public Long getProfileId()
	{
		return dbprofile_id;
	}
	/** toString method*/
	public String toString()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("\n[\n");
		sResult.append( "\t id : " ).append( getId()).append("\n");
		sResult.append( "\t name : " ).append( getName()).append("\n");
		sResult.append( "\t login : " ).append( getLogin()).append("\n");
		sResult.append( "\t password : " ).append( getPassword()).append("\n");
		sResult.append( "\t creationDate : " ).append( getCreationDate()).append("\n");
		sResult.append( "\t lastLoginDate : " ).append( getLastLoginDate()).append("\n");
		sResult.append( "\t status : " ).append( getStatus()).append("\n");
		sResult.append( "\t profileId : " ).append( getProfileId()).append("\n");
		sResult.append("]\n");
		return sResult.toString();
	}

	/** toMap method*/
	public java.util.Map<String,Object> toMap()
	{

		java.util.Map<String,Object> map = new java.util.HashMap<String,Object>();
		map.put( "id" , String.valueOf(getId()));
		map.put( "name" , String.valueOf(getName()));
		map.put( "login" , String.valueOf(getLogin()));
		map.put( "password" , String.valueOf(getPassword()));
		map.put( "creationDate" , String.valueOf(getCreationDate()));
		map.put( "lastLoginDate" , String.valueOf(getLastLoginDate()));
		map.put( "status" , String.valueOf(getStatus()));
		map.put( "profileId" , String.valueOf(getProfileId()));
		return map;
	}

	/** toJSon method*/
	public String toJSon()
	{

		StringBuffer sResult = new StringBuffer();
		sResult.append("{");
		sResult.append( "\"id\":\"" ).append(String.valueOf(getId()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"name\":\"" ).append(String.valueOf(getName()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"login\":\"" ).append(String.valueOf(getLogin()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"password\":\"" ).append(String.valueOf(getPassword()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"creationDate\":\"" ).append(String.valueOf(getCreationDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"lastLoginDate\":\"" ).append(String.valueOf(getLastLoginDate()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"status\":\"" ).append(String.valueOf(getStatus()) ).append("\"");
		sResult.append( ",");
		sResult.append( "\"profileId\":\"" ).append(String.valueOf(getProfileId()) ).append("\"");
		sResult.append("}");
		return sResult.toString();
	}

	/** toList method*/
	public java.util.List<String> toList()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( String.valueOf(getId()));
		list.add( String.valueOf(getName()));
		list.add( String.valueOf(getLogin()));
		list.add( String.valueOf(getPassword()));
		list.add( String.valueOf(getCreationDate()));
		list.add( String.valueOf(getLastLoginDate()));
		list.add( String.valueOf(getStatus()));
		list.add( String.valueOf(getProfileId()));
		return list;
	}

	/** getAttributeNames method*/
	public java.util.List<String> getAttributeNames()
	{

		java.util.List<String> list = new java.util.ArrayList<String>();
		list.add( "id");
		list.add( "name");
		list.add( "login");
		list.add( "password");
		list.add( "creationDate");
		list.add( "lastLoginDate");
		list.add( "status");
		list.add( "profileId");
		return list;
	}

}
	//** Database fields
