// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.test.meta;

// import NeoDatis Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import java.util.Date;

import java.math.BigDecimal;

public class ConfiguracaoDBHelper{
	public static final DBTable table = new DefaultDBTable("CONFIGURACAO");

	public static final DBColumn ID =  new DefaultDBColumn( table , "ID" , Long.class );
	public static final DBColumn CODIGO =  new DefaultDBColumn( table , "CODIGO" , String.class );
	public static final DBColumn VALOR =  new DefaultDBColumn( table , "VALOR" , String.class );
	public static final DBColumn DESCRICAO =  new DefaultDBColumn( table , "DESCRICAO" , String.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[4];
		array[0] = ID;
		array[1] = CODIGO;
		array[2] = VALOR;
		array[3] = DESCRICAO;
		return array;
	}
}
