// class generated by NeoDatis Database ClassBuilder 2.0
package org.neodatis.rdb.test.meta;

// import NeoDatis Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import java.util.Date;

import java.math.BigDecimal;

public class EventoDBHelper{
	public static final DBTable table = new DefaultDBTable("EVENTIS_EVENTO");

	public static final DBColumn ID =  new DefaultDBColumn( table , "ID" , Long.class );
	public static final DBColumn UUID =  new DefaultDBColumn( table , "UUID" , String.class );
	public static final DBColumn NUMERO =  new DefaultDBColumn( table , "NUMERO" , Long.class );
	public static final DBColumn ID_CATEGORIA =  new DefaultDBColumn( table , "ID_CATEGORIA" , Long.class );
	public static final DBColumn ID_TIPO =  new DefaultDBColumn( table , "ID_TIPO" , Long.class );
	public static final DBColumn ID_SUB_TIPO =  new DefaultDBColumn( table , "ID_SUB_TIPO" , Long.class );
	public static final DBColumn ID_CENTRO_CONTROLE =  new DefaultDBColumn( table , "ID_CENTRO_CONTROLE" , Long.class );
	public static final DBColumn OBSERVACAO =  new DefaultDBColumn( table , "OBSERVACAO" , String.class );
	public static final DBColumn ID_ESTADO =  new DefaultDBColumn( table , "ID_ESTADO" , Long.class );
	public static final DBColumn ID_RODOVIA =  new DefaultDBColumn( table , "ID_RODOVIA" , Long.class );
	public static final DBColumn ID_SENTIDO =  new DefaultDBColumn( table , "ID_SENTIDO" , Long.class );
	public static final DBColumn FAIXA =  new DefaultDBColumn( table , "FAIXA" , Long.class );
	public static final DBColumn KM =  new DefaultDBColumn( table , "KM" , BigDecimal.class );
	public static final DBColumn ENDERECO =  new DefaultDBColumn( table , "ENDERECO" , String.class );
	public static final DBColumn REFERENCIA_ENDERECO =  new DefaultDBColumn( table , "REFERENCIA_ENDERECO" , String.class );
	public static final DBColumn LONGITUDE =  new DefaultDBColumn( table , "LONGITUDE" , BigDecimal.class );
	public static final DBColumn LATITUDE =  new DefaultDBColumn( table , "LATITUDE" , BigDecimal.class );
	public static final DBColumn DATA_HORA_CRIACAO_EVENTO =  new DefaultDBColumn( table , "DATA_HORA_CRIACAO_EVENTO" , Date.class );
	public static final DBColumn DATA_HORA_INICIO_EVENTO =  new DefaultDBColumn( table , "DATA_HORA_INICIO_EVENTO" , Date.class );
	public static final DBColumn DATA_HORA_ATUALIZACAO_EVENTO =  new DefaultDBColumn( table , "DATA_HORA_ATUALIZACAO_EVENTO" , Date.class );
	public static final DBColumn DATA_HORA_TERMINO_DIGITADO =  new DefaultDBColumn( table , "DATA_HORA_TERMINO_DIGITADO" , Date.class );
	public static final DBColumn PRIORIDADE =  new DefaultDBColumn( table , "PRIORIDADE" , Long.class );
	public static final DBColumn ID_ORIGEM_EVENTO =  new DefaultDBColumn( table , "ID_ORIGEM_EVENTO" , Long.class );
	public static final DBColumn DESCRICAO_ORIGEM_EVENTO =  new DefaultDBColumn( table , "DESCRICAO_ORIGEM_EVENTO" , String.class );
	public static final DBColumn ID_SITUACAO_EVENTO =  new DefaultDBColumn( table , "ID_SITUACAO_EVENTO" , Long.class );
	public static final DBColumn ID_RAZAO_FECHAMENTO =  new DefaultDBColumn( table , "ID_RAZAO_FECHAMENTO" , Long.class );
	public static final DBColumn ID_OPERADOR_RESPONSAVEL =  new DefaultDBColumn( table , "ID_OPERADOR_RESPONSAVEL" , Long.class );
	public static final DBColumn ID_EXTERNO =  new DefaultDBColumn( table , "ID_EXTERNO" , String.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DefaultDBColumn[28];
		array[0] = ID;
		array[1] = UUID;
		array[2] = NUMERO;
		array[3] = ID_CATEGORIA;
		array[4] = ID_TIPO;
		array[5] = ID_SUB_TIPO;
		array[6] = ID_CENTRO_CONTROLE;
		array[7] = OBSERVACAO;
		array[8] = ID_ESTADO;
		array[9] = ID_RODOVIA;
		array[10] = ID_SENTIDO;
		array[11] = FAIXA;
		array[12] = KM;
		array[13] = ENDERECO;
		array[14] = REFERENCIA_ENDERECO;
		array[15] = LONGITUDE;
		array[16] = LATITUDE;
		array[17] = DATA_HORA_CRIACAO_EVENTO;
		array[18] = DATA_HORA_INICIO_EVENTO;
		array[19] = DATA_HORA_ATUALIZACAO_EVENTO;
		array[20] = DATA_HORA_TERMINO_DIGITADO;
		array[21] = PRIORIDADE;
		array[22] = ID_ORIGEM_EVENTO;
		array[23] = DESCRICAO_ORIGEM_EVENTO;
		array[24] = ID_SITUACAO_EVENTO;
		array[25] = ID_RAZAO_FECHAMENTO;
		array[26] = ID_OPERADOR_RESPONSAVEL;
		array[27] = ID_EXTERNO;
		return array;
	}
}
