// class generated by NeoDatis Database ClassBuilder 2.0
package com.mycompany.myobjects.metadata;

// import NeoDatis Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import java.util.Date;

import java.math.BigDecimal;

public class ControlePracaDBHelper{
	public static final DBTable table = new DefaultDBTable("CONTROLE_COMUNICACAO_PRACA");

	public static final DBColumn ID =  new DefaultDBColumn( table , "ID" , Long.class );
	public static final DBColumn ID_PRACA =  new DefaultDBColumn( table , "ID_PRACA" , Long.class );
	public static final DBColumn NOME_PRACA =  new DefaultDBColumn( table , "NOME_PRACA" , String.class );
	public static final DBColumn DATA_HORA_ULTIMA_COMUNICACAO =  new DefaultDBColumn( table , "DATA_HORA_ULTIMA_COMUNICACAO" , Date.class );
	public static final DBColumn DESCRICAO_MSG =  new DefaultDBColumn( table , "DESCRICAO_MSG" , String.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DBColumn[5];
		array[0] = ID;
		array[1] = ID_PRACA;
		array[2] = NOME_PRACA;
		array[3] = DATA_HORA_ULTIMA_COMUNICACAO;
		array[4] = DESCRICAO_MSG;
		return array;
	}
}
