// class generated by NeoDatis Database ClassBuilder 2.0
package com.mycompany.myobjects.metadata;

// import NeoDatis Database library
import org.neodatis.rdb.*;

import org.neodatis.rdb.query.*;

import java.util.Date;

import java.math.BigDecimal;

public class TransferenciaArquivoDBHelper{
	public static final DBTable table = new DefaultDBTable("TRANSFERENCIA_ARQUIVO");

	public static final DBColumn ID =  new DefaultDBColumn( table , "ID" , Long.class );
	public static final DBColumn DATA_HORA_INICIO_TRANSFERENCIA =  new DefaultDBColumn( table , "DATA_HORA_INICIO_TRANSFERENCIA" , Date.class );
	public static final DBColumn NOME_DIRETORIO_ORIGINAL =  new DefaultDBColumn( table , "NOME_DIRETORIO_ORIGINAL" , String.class );
	public static final DBColumn NOME_ARQUIVO_ORIGINAL =  new DefaultDBColumn( table , "NOME_ARQUIVO_ORIGINAL" , String.class );
	public static final DBColumn NOME_ARQUIVO_FORNECEDOR =  new DefaultDBColumn( table , "NOME_ARQUIVO_FORNECEDOR" , String.class );
	public static final DBColumn TAMANHO_ARQUIVO_ORIGINAL =  new DefaultDBColumn( table , "TAMANHO_ARQUIVO_ORIGINAL" , Long.class );
	public static final DBColumn CRC_ORIGEM =  new DefaultDBColumn( table , "CRC_ORIGEM" , Long.class );
	public static final DBColumn DATA_HORA_FIM_TRANSFERENCIA =  new DefaultDBColumn( table , "DATA_HORA_FIM_TRANSFERENCIA" , Date.class );
	public static final DBColumn NOME_DIRETORIO_DESTINO =  new DefaultDBColumn( table , "NOME_DIRETORIO_DESTINO" , String.class );
	public static final DBColumn NOME_ARQUIVO_DESTINO =  new DefaultDBColumn( table , "NOME_ARQUIVO_DESTINO" , String.class );
	public static final DBColumn TAMANHO_ARQUIVO_DESTINO =  new DefaultDBColumn( table , "TAMANHO_ARQUIVO_DESTINO" , Long.class );
	public static final DBColumn CRC_DESTINO =  new DefaultDBColumn( table , "CRC_DESTINO" , Long.class );
	public static final DBColumn TRANSFERENCIA_OK =  new DefaultDBColumn( table , "TRANSFERENCIA_OK" , Long.class );
	public static final DBColumn ESTADO =  new DefaultDBColumn( table , "ESTADO" , Long.class );
	public static final DBColumn DATA_HORA_PROCESSAMENTO =  new DefaultDBColumn( table , "DATA_HORA_PROCESSAMENTO" , Date.class );
	public static final DBColumn DURACAO_PROCESSAMENTO_MS =  new DefaultDBColumn( table , "DURACAO_PROCESSAMENTO_MS" , Long.class );
	public static final DBColumn NUMERO_TRANSACOES =  new DefaultDBColumn( table , "NUMERO_TRANSACOES" , Long.class );
	public static final DBColumn NUMERO_ALERTAS =  new DefaultDBColumn( table , "NUMERO_ALERTAS" , Long.class );
	public static final DBColumn ID_PRACA =  new DefaultDBColumn( table , "ID_PRACA" , Long.class );

	//** To get the column list
	static public DBColumn [] getColumns()
	{
		DBColumn [] array = new DBColumn[19];
		array[0] = ID;
		array[1] = DATA_HORA_INICIO_TRANSFERENCIA;
		array[2] = NOME_DIRETORIO_ORIGINAL;
		array[3] = NOME_ARQUIVO_ORIGINAL;
		array[4] = NOME_ARQUIVO_FORNECEDOR;
		array[5] = TAMANHO_ARQUIVO_ORIGINAL;
		array[6] = CRC_ORIGEM;
		array[7] = DATA_HORA_FIM_TRANSFERENCIA;
		array[8] = NOME_DIRETORIO_DESTINO;
		array[9] = NOME_ARQUIVO_DESTINO;
		array[10] = TAMANHO_ARQUIVO_DESTINO;
		array[11] = CRC_DESTINO;
		array[12] = TRANSFERENCIA_OK;
		array[13] = ESTADO;
		array[14] = DATA_HORA_PROCESSAMENTO;
		array[15] = DURACAO_PROCESSAMENTO_MS;
		array[16] = NUMERO_TRANSACOES;
		array[17] = NUMERO_ALERTAS;
		array[18] = ID_PRACA;
		return array;
	}
}
